const group4: { [key: string]: string } = {
  "INF121A014T1": "Bank of India Arbitrage Fund(G)-Direct Plan",
  "INF121A014U9": "Bank of India Arbitrage Fund(IDCW)-Direct Plan",
  "INF121A014V7": "Bank of India Arbitrage Fund(M-IDCW)-Direct Plan",
  "INF121A014Q7": "Bank of India Arbitrage Fund-Reg(G)",
  "INF121A014R5": "Bank of India Arbitrage Fund-Reg(IDCW)",
  "INF121A014S3": "Bank of India Arbitrage Fund-Reg(M-IDCW)",
  "INF121A012X7": "Bank of India Balanced Advantage Fund(G)-Direct Plan",
  "INF121A012Y5": "Bank of India Balanced Advantage Fund(IDCW)-Direct Plan",
  "INF121A012V1": "Bank of India Balanced Advantage Fund-Reg(G)",
  "INF121A012W9": "Bank of India Balanced Advantage Fund-Reg(IDCW)",
  "INF121A016A6": "Bank of India Bluechip Fund(G)-Direct Plan",
  "INF121A016B4": "Bank of India Bluechip Fund(IDCW)-Direct Plan",
  "INF121A014A7": "Bank of India Bluechip Fund-Reg(G)",
  "INF121A015A4": "Bank of India Bluechip Fund-Reg(IDCW)",
  "INF121A018B0": "Bank of India Conservative Hybrid Fund(G)-Direct Plan",
  "INF121A018C8": "Bank of India Conservative Hybrid Fund(M-IDCW)-Direct Plan",
  "INF121A018D6": "Bank of India Conservative Hybrid Fund(Q-IDCW)-Direct Plan",
  "INF121A017X0": "Bank of India Conservative Hybrid Fund-Reg(G)",
  "INF121A017Y8": "Bank of India Conservative Hybrid Fund-Reg(M-IDCW)",
  "INF121A017Z5": "Bank of India Conservative Hybrid Fund-Reg(Q-IDCW)",
  "INF121A011X9": "Bank of India ELSS Tax Saver Fund(G)-Direct Plan",
  "INF121A011Y7": "Bank of India ELSS Tax Saver Fund(IDCW)-Direct Plan",
  "INF121A011V3": "Bank of India ELSS Tax Saver Fund-Reg(G)",
  "INF121A011W1": "Bank of India ELSS Tax Saver Fund-Reg(IDCW)",
  "INF121A019B8": "Bank of India Flexi Cap Fund(G)-Direct Plan",
  "INF121A019C6": "Bank of India Flexi Cap Fund(IDCW)-Direct Plan",
  "INF121A018X8": "Bank of India Flexi Cap Fund-Reg(G)",
  "INF121A019A0": "Bank of India Flexi Cap Fund-Reg(IDCW)",
  "INF121A010J3": "Bank of India Large & Mid Cap Equity Fund(G)-Direct Plan",
  "INF121A011J1": "Bank of India Large & Mid Cap Equity Fund(IDCW)-Direct Plan",
  "INF121A018I5": "Bank of India Large & Mid Cap Equity Fund-Reg(G)",
  "INF121A019I3": "Bank of India Large & Mid Cap Equity Fund-Reg(IDCW)",
  "INF121A011S0": "Bank of India Liquid Fund(DD-IDCW)-Direct Plan",
  "INF121A010S2": "Bank of India Liquid Fund(G)-Direct Plan",
  "INF121A012S8": "Bank of India Liquid Fund(W-IDCW)-Direct Plan",
  "INF121A014H4": "Bank of India Liquid Fund-Reg(DD-IDCW)",
  "INF121A010H6": "Bank of India Liquid Fund-Reg(G)",
  "INF121A015H1": "Bank of India Liquid Fund-Reg(W-IDCW)",
  "INF121A019V0": "Bank of India Mid & Small Cap Equity & Debt Fund(G)-Direct Plan",
  "INF121A019W8": "Bank of India Mid & Small Cap Equity & Debt Fund(IDCW)-Direct Plan",
  "INF121A019X6": "Bank of India Mid & Small Cap Equity & Debt Fund(M-IDCW)-Direct Plan",
  "INF121A019S6": "Bank of India Mid & Small Cap Equity & Debt Fund-Reg(G)",
  "INF121A019T4": "Bank of India Mid & Small Cap Equity & Debt Fund-Reg(IDCW)",
  "INF121A019U2": "Bank of India Mid & Small Cap Equity & Debt Fund-Reg(M-IDCW)",
  "INF121A012H0": "Bank of India Small Cap Fund(G)-Direct Plan",
  "INF121A013H8": "Bank of India Small Cap Fund(IDCW)-Direct Plan",
  "INF121A010H4": "Bank of India Small Cap Fund-Reg(G)",
  "INF121A011H2": "Bank of India Small Cap Fund-Reg(IDCW)",
  "INF121A019T8": "Bank of India Ultra Short Duration Fund(DD-IDCW)-Direct Plan",
  "INF121A018T0": "Bank of India Ultra Short Duration Fund(G)-Direct Plan",
  "INF121A010U3": "Bank of India Ultra Short Duration Fund(W-IDCW)-Direct Plan",
  "INF121A013I7": "Bank of India Ultra Short Duration Fund-Reg(DD-IDCW)",
  "INF121A011I9": "Bank of India Ultra Short Duration Fund-Reg(G)",
  "INF121A014I5": "Bank of India Ultra Short Duration Fund-Reg(W-IDCW)",
  "INF843K01FN8": "Baroda BNP Paribas Arbitrage Fund(G)-Direct Plan",
  "INF843K01FO6": "Baroda BNP Paribas Arbitrage Fund(IDCW)-Direct Plan",
  "INF843K01FK4": "Baroda BNP Paribas Arbitrage Fund-Reg(G)",
  "INF843K01FL2": "Baroda BNP Paribas Arbitrage Fund-Reg(IDCW)",
  "INF843K01FE7": "Baroda BNP Paribas Balanced Advantage Fund(G)-Direct Plan",
  "INF843K01FF4": "Baroda BNP Paribas Balanced Advantage Fund(IDCW)-Direct Plan",
  "INF843K01FA5": "Baroda BNP Paribas Balanced Advantage Fund-Reg(G)",
  "INF843K01FB3": "Baroda BNP Paribas Balanced Advantage Fund-Reg(IDCW)",
  "INF843K01HI9": "Baroda BNP Paribas Banking & Financial Services Fund(G)-Direct Plan",
  "INF843K01HJ7": "Baroda BNP Paribas Banking & Financial Services Fund(IDCW)-Direct Plan",
  "INF843K01HE8": "Baroda BNP Paribas Banking & Financial Services Fund-Reg(G)",
  "INF843K01HF5": "Baroda BNP Paribas Banking & Financial Services Fund-Reg(IDCW)",
  "INF843K01DR5": "Baroda BNP Paribas Low Duration Fund-Reg(G)",
  "INF843K01DS3": "Baroda BNP Paribas Low Duration Fund-Reg(W-IDCW)",
  "INF843K01DN4": "Baroda BNP Paribas Banking & PSU Bond Fund-Reg(G)",
  "INF843K01DO2": "Baroda BNP Paribas Banking & PSU Bond Fund-Reg(IDCW)",
  "INF843K01HQ2": "Baroda BNP Paribas Conservative Hybrid Fund(G)-Direct Plan",
  "INF843K01HR0": "Baroda BNP Paribas Conservative Hybrid Fund(M-IDCW)-Direct Plan",
  "INF843K01HS8": "Baroda BNP Paribas Conservative Hybrid Fund(Q-IDCW)-Direct Plan",
  "INF843K01HM1": "Baroda BNP Paribas Conservative Hybrid Fund-Reg(G)",
  "INF843K01HN9": "Baroda BNP Paribas Conservative Hybrid Fund-Reg(M-IDCW)",
  "INF843K01HO7": "Baroda BNP Paribas Conservative Hybrid Fund-Reg(Q-IDCW)",
  "INF843K01DZ8": "Baroda BNP Paribas Corporate Bond Fund(G)-Direct Plan",
  "INF843K01EA9": "Baroda BNP Paribas Corporate Bond Fund(IDCW)-Direct Plan",
  "INF843K01DV7": "Baroda BNP Paribas Low Duration Fund(G)-Direct Plan",
  "INF843K01DW5": "Baroda BNP Paribas Low Duration Fund(W-IDCW)-Direct Plan",
  "INF843K01EM9": "Baroda BNP Paribas Credit Risk Fund(G)-Direct Plan",
  "INF843K01EN7": "Baroda BNP Paribas Credit Risk Fund(IDCW)-Direct Plan",
  "INF843K01EI7": "Baroda BNP Paribas Credit Risk Fund-Reg(G)",
  "INF843K01EJ5": "Baroda BNP Paribas Credit Risk Fund-Reg(IDCW)",
  "INF843K01EO5": "Baroda BNP Paribas Dynamic Bond Fund(G)-Direct Plan",
  "INF843K01EP2": "Baroda BNP Paribas Dynamic Bond Fund(IDCW)-Direct Plan",
  "INF843K01EK3": "Baroda BNP Paribas Dynamic Bond Fund-Reg(G)",
  "INF843K01EL1": "Baroda BNP Paribas Dynamic Bond Fund-Reg(IDCW)",
  "INF843K01GD7": "Baroda BNP Paribas ELSS Tax Saver Fund(G)-Direct Plan",
  "INF843K01GE5": "Baroda BNP Paribas ELSS Tax Saver Fund(IDCW)-Direct Plan",
  "INF843K01GB1": "Baroda BNP Paribas ELSS Tax Saver Fund-Reg(G)",
  "INF843K01GC9": "Baroda BNP Paribas ELSS Tax Saver Fund-Reg(IDCW)",
  "INF843K01GJ4": "Baroda BNP Paribas Flexi Cap Fund(G)-Direct Plan",
  "INF843K01GK2": "Baroda BNP Paribas Flexi Cap Fund(IDCW)-Direct Plan",
  "INF843K01GH8": "Baroda BNP Paribas Flexi Cap Fund-Reg(G)",
  "INF843K01GI6": "Baroda BNP Paribas Flexi Cap Fund-Reg(IDCW)",
  "INF843K01GP1": "Baroda BNP Paribas Focused 25 Fund(G)-Direct Plan",
  "INF843K01GQ9": "Baroda BNP Paribas Focused 25 Fund(IDCW)-Direct Plan",
  "INF843K01GN6": "Baroda BNP Paribas Focused 25 Fund-Reg(G)",
  "INF843K01GO4": "Baroda BNP Paribas Focused 25 Fund-Reg(IDCW)",
  "INF843K01HD0": "Baroda BNP Paribas Gilt Fund(G)-Direct Plan",
  "INF843K01HC2": "Baroda BNP Paribas Gilt Fund-Reg(G)",
  "INF843K01GW7": "Baroda BNP Paribas Large & Mid Cap Fund(G)-Direct Plan",
  "INF843K01GX5": "Baroda BNP Paribas Large & Mid Cap Fund(IDCW)-Direct Plan",
  "INF843K01GU1": "Baroda BNP Paribas Large & Mid Cap Fund-Reg(G)",
  "INF843K01GV9": "Baroda BNP Paribas Large & Mid Cap Fund-Reg(IDCW)",
  "INF843K01GR7": "Baroda BNP Paribas Large Cap Fund(G)-Direct Plan",
  "INF843K01GS5": "Baroda BNP Paribas Large Cap Fund(IDCW)-Direct Plan",
  "INF843K01GT3": "Baroda BNP Paribas Large Cap Fund-Reg(G)",
  "INF843K01FU3": "Baroda BNP Paribas Large Cap Fund-Reg(IDCW)",
  "INF843K01DP9": "Baroda BNP Paribas Liquid Fund(DD-IDCW)-Direct Plan",
  "INF843K01DN0": "Baroda BNP Paribas Liquid Fund(G)-Direct Plan",
  "INF843K01DO8": "Baroda BNP Paribas Liquid Fund(W-IDCW)-Direct Plan",
  "INF843K01DL4": "Baroda BNP Paribas Liquid Fund-Reg(DD-IDCW)",
  "INF843K01DJ8": "Baroda BNP Paribas Liquid Fund-Reg(G)",
  "INF843K01DK6": "Baroda BNP Paribas Liquid Fund-Reg(W-IDCW)",
  "INF843K01DY1": "Baroda BNP Paribas Low Duration Fund(DD-IDCW)-Direct Plan",
  "INF843K01DT1": "Baroda BNP Paribas Low Duration Fund-Reg(DD-IDCW)",
  "INF843K01GZ0": "Baroda BNP Paribas Mid Cap Fund(G)-Direct Plan",
  "INF843K01HA6": "Baroda BNP Paribas Mid Cap Fund(IDCW)-Direct Plan",
  "INF843K01GY3": "Baroda BNP Paribas Mid Cap Fund-Reg(G)",
  "INF843K01G97": "Baroda BNP Paribas Mid Cap Fund-Reg(IDCW)",
  "INF843K01ES6": "Baroda BNP Paribas Money Market Fund(G)-Direct Plan",
  "INF843K01ET4": "Baroda BNP Paribas Money Market Fund(IDCW)-Direct Plan",
  "INF843K01EO4": "Baroda BNP Paribas Money Market Fund-Reg(G)",
  "INF843K01EP1": "Baroda BNP Paribas Money Market Fund-Reg(IDCW)",
  "INF843K01IP8": "Baroda BNP Paribas Multi Asset Allocation Fund(G)-Direct Plan",
  "INF843K01IQ6": "Baroda BNP Paribas Multi Asset Allocation Fund(IDCW)-Direct Plan",
  "INF843K01IL7": "Baroda BNP Paribas Multi Asset Allocation Fund-Reg(G)",
  "INF843K01IM5": "Baroda BNP Paribas Multi Asset Allocation Fund-Reg(IDCW)",
  "INF843K01IO1": "Baroda BNP Paribas Multi Cap Fund(G)-Direct Plan",
  "INF843K01IN3": "Baroda BNP Paribas Multi Cap Fund-Reg(G)",
  "INF843K01DB3": "Baroda BNP Paribas Overnight Fund(DD-IDCW)-Direct Plan",
  "INF843K01DA5": "Baroda BNP Paribas Overnight Fund(G)-Direct Plan",
  "INF843K01CY9": "Baroda BNP Paribas Overnight Fund-Reg(DD-IDCW)",
  "INF843K01CX1": "Baroda BNP Paribas Overnight Fund-Reg(G)",
  "INF843K01FC1": "Baroda BNP Paribas Small Cap Fund(G)-Direct Plan",
  "INF843K01FD9": "Baroda BNP Paribas Small Cap Fund(IDCW)-Direct Plan",
  "INF843K01FY5": "Baroda BNP Paribas Small Cap Fund-Reg(G)",
  "INF843K01FZ2": "Baroda BNP Paribas Small Cap Fund-Reg(IDCW)",
  "INF843K01EE8": "Baroda BNP Paribas Ultra Short Duration Fund(DD-IDCW)-Direct Plan",
  "INF843K01EB4": "Baroda BNP Paribas Ultra Short Duration Fund(G)-Direct Plan",
  "INF843K01EC2": "Baroda BNP Paribas Ultra Short Duration Fund(W-IDCW)-Direct Plan",
  "INF843K01DZ7": "Baroda BNP Paribas Ultra Short Duration Fund-Reg(DD-IDCW)",
  "INF843K01DX2": "Baroda BNP Paribas Ultra Short Duration Fund-Reg(G)",
  "INF843K01DY0": "Baroda BNP Paribas Ultra Short Duration Fund-Reg(W-IDCW)",
  "INF760K01EH6": "Canara Robeco Balanced Advantage Fund-Reg(G)",
  "INF760K01EI4": "Canara Robeco Balanced Advantage Fund-Reg(IDCW)",
  "INF760K01EJ2": "Canara Robeco Balanced Advantage Fund(G)-Direct Plan",
  "INF760K01EE2": "Canara Robeco Liquid Fund(W-IDCW)-Direct Plan",
  "INF760K01EF9": "Canara Robeco Liquid Fund-Reg(DD-IDCW)",
  "INF760K01EG7": "Canara Robeco Arbitrage Fund-Reg(M-IDCW)",
  "INF760K01EK0": "Canara Robeco Balanced Advantage Fund(IDCW)-Direct Plan",
  "INF760K01EO0": "Canara Robeco Bluechip Equity Fund(G)-Direct Plan",
  "INF760K01EP7": "Canara Robeco Bluechip Equity Fund(IDCW)-Direct Plan",
  "INF760K01EM4": "Canara Robeco Bluechip Equity Fund-Reg(G)",
  "INF760K01EN2": "Canara Robeco Bluechip Equity Fund-Reg(IDCW)",
  "INF760K01968": "Canara Robeco Conservative Hybrid Fund(G)-Direct Plan",
  "INF760K01976": "Canara Robeco Conservative Hybrid Fund(M-IDCW)-Direct Plan",
  "INF760K01984": "Canara Robeco Conservative Hybrid Fund(Q-IDCW)-Direct Plan",
  "INF760K01950": "Canara Robeco Conservative Hybrid Fund-Reg(G)",
  "INF760K01109": "Canara Robeco Conservative Hybrid Fund-Reg(M-IDCW)",
  "INF760K01125": "Canara Robeco Conservative Hybrid Fund-Reg(Q-IDCW)",
  "INF760K01DU3": "Canara Robeco Corporate Bond Fund(G)-Direct Plan",
  "INF760K01DV1": "Canara Robeco Corporate Bond Fund(IDCW)-Direct Plan",
  "INF760K01DR9": "Canara Robeco Corporate Bond Fund-Reg(G)",
  "INF760K01DS7": "Canara Robeco Corporate Bond Fund-Reg(IDCW)",
  "INF760K01DC7": "Canara Robeco Credit Risk Fund(G)-Direct Plan",
  "INF760K01DD5": "Canara Robeco Credit Risk Fund(IDCW)-Direct Plan",
  "INF760K01CY5": "Canara Robeco Credit Risk Fund-Reg(G)",
  "INF760K01CZ2": "Canara Robeco Credit Risk Fund-Reg(IDCW)",
  "INF760K01DS1": "Canara Robeco Dynamic Bond Fund(G)-Direct Plan",
  "INF760K01DT9": "Canara Robeco Dynamic Bond Fund(IDCW)-Direct Plan",
  "INF760K01DP7": "Canara Robeco Dynamic Bond Fund-Reg(G)",
  "INF760K01DQ5": "Canara Robeco Dynamic Bond Fund-Reg(IDCW)",
  "INF760K01EX2": "Canara Robeco ELSS Tax Saver Fund(G)-Direct Plan",
  "INF760K01EY0": "Canara Robeco ELSS Tax Saver Fund(IDCW)-Direct Plan",
  "INF760K01EV6": "Canara Robeco ELSS Tax Saver Fund-Reg(G)",
  "INF760K01EW4": "Canara Robeco ELSS Tax Saver Fund-Reg(IDCW)",
  "INF760K01ER4": "Canara Robeco Equity Hybrid Fund(G)-Direct Plan",
  "INF760K01ES2": "Canara Robeco Equity Hybrid Fund(IDCW)-Direct Plan",
  "INF760K01EP8": "Canara Robeco Equity Hybrid Fund-Reg(G)",
  "INF760K01EQ6": "Canara Robeco Equity Hybrid Fund-Reg(IDCW)",
  "INF760K01FF7": "Canara Robeco Flexi Cap Fund(G)-Direct Plan",
  "INF760K01FG5": "Canara Robeco Flexi Cap Fund(IDCW)-Direct Plan",
  "INF760K01FD2": "Canara Robeco Flexi Cap Fund-Reg(G)",
  "INF760K01FE0": "Canara Robeco Flexi Cap Fund-Reg(IDCW)",
  "INF760K01EG1": "Canara Robeco Gilt Fund(G)-Direct Plan",
  "INF760K01EH9": "Canara Robeco Gilt Fund(IDCW)-Direct Plan",
  "INF760K01EE6": "Canara Robeco Ultra Short Term Debt Fund-Reg(G)",
  "INF760K01EF3": "Canara Robeco Gilt Fund-Reg(IDCW)",
  "INF760K01HN6": "Canara Robeco Infrastructure Fund(G)-Direct Plan",
  "INF760K01HO4": "Canara Robeco Infrastructure Fund(IDCW)-Direct Plan",
  "INF760K01HL0": "Canara Robeco Infrastructure Fund-Reg(G)",
  "INF760K01HM8": "Canara Robeco Infrastructure Fund-Reg(IDCW)",
  "INF760K01EA9": "Canara Robeco Large & Mid Cap Fund(G)-Direct Plan",
  "INF760K01EB7": "Canara Robeco Large & Mid Cap Fund(IDCW)-Direct Plan",
  "INF760K01885": "Canara Robeco Large & Mid Cap Fund-Reg(G)",
  "INF760K01893": "Canara Robeco Large & Mid Cap Fund-Reg(IDCW)",
  "INF760K01EK2": "Canara Robeco Liquid Fund(DD-IDCW)-Direct Plan",
  "INF760K01EC6": "Canara Robeco Liquid Fund(G)-Direct Plan",
  "INF760K01CF0": "Canara Robeco Liquid Fund-Reg(G)",
  "INF760K01CG8": "Canara Robeco Liquid Fund-Reg(W-IDCW)",
  "INF760K01DP4": "Canara Robeco Short Duration Fund(G)-Direct Plan",
  "INF760K01DQ2": "Canara Robeco Short Duration Fund(IDCW)-Direct Plan",
  "INF760K01DM0": "Canara Robeco Short Duration Fund-Reg(G)",
  "INF760K01DN8": "Canara Robeco Short Duration Fund-Reg(IDCW)",
  "INF760K01EB5": "Canara Robeco Small Cap Fund(G)-Direct Plan",
  "INF760K01EC3": "Canara Robeco Small Cap Fund(IDCW)-Direct Plan",
  "INF760K01DY0": "Canara Robeco Small Cap Fund-Reg(G)",
  "INF760K01DZ7": "Canara Robeco Small Cap Fund-Reg(IDCW)",
  "INF760K01ET0": "Canara Robeco Ultra Short Term Debt Fund(DD-IDCW)-Direct Plan",
  "INF760K01EM5": "Canara Robeco Ultra Short Term Debt Fund(G)-Direct Plan",
  "INF760K01EN3": "Canara Robeco Ultra Short Term Debt Fund(W-IDCW)-Direct Plan",
  "INF760K01EL7": "Canara Robeco Ultra Short Term Debt Fund-Reg(DD-IDCW)",
  "INF760K01EJ1": "Canara Robeco Ultra Short Term Debt Fund-Reg(W-IDCW)",
};
export default group4;
