const group1: { [key: string]: string } = {
  "INF579M01266": "360 ONE Dynamic Bond Fund(G)-Direct Plan",
  "INF579M01282": "360 ONE Dynamic Bond Fund(M-IDCW Payout)-Direct Plan",
  "INF579M01316": "360 ONE Dynamic Bond Fund(M-IDCW)-Direct Plan",
  "INF579M01290": "360 ONE Dynamic Bond Fund(Q-IDCW Payout)-Direct Plan",
  "INF579M01324": "360 ONE Dynamic Bond Fund(Q-IDCW)-Direct Plan",
  "INF579M01183": "360 ONE Dynamic Bond Fund-Reg(G)",
  "INF579M01225": "360 ONE Dynamic Bond Fund-Reg(H-IDCW Payout)",
  "INF579M01258": "360 ONE Dynamic Bond Fund-Reg(H-IDCW)",
  "INF579M01209": "360 ONE Dynamic Bond Fund-Reg(M-IDCW Payout)",
  "INF579M01233": "360 ONE Dynamic Bond Fund-Reg(M-IDCW)",
  "INF579M01217": "360 ONE Dynamic Bond Fund-Reg(Q-IDCW Payout)",
  "INF579M01241": "360 ONE Dynamic Bond Fund-Reg(Q-IDCW)",
  "INF579M01AN2": "360 ONE ELSS Tax Saver Nifty 50 Index Fund(G)-Direct Plan",
  "INF579M01AO0": "360 ONE ELSS Tax Saver Nifty 50 Index Fund(IDCW)-Direct Plan",
  "INF579M01AL6": "360 ONE ELSS Tax Saver Nifty 50 Index Fund-Reg(G)",
  "INF579M01AM4": "360 ONE ELSS Tax Saver Nifty 50 Index Fund-Reg(IDCW)",
  "INF579M01AS1": "360 ONE Flexicap Fund(G)-Direct Plan",
  "INF579M01AT9": "360 ONE Flexicap Fund(IDCW Payout)-Direct Plan",
  "INF579M01AU7": "360 ONE Flexicap Fund(IDCW)-Direct Plan",
  "INF579M01AP7": "360 ONE Flexicap Fund-Reg(G)",
  "INF579M01AQ5": "360 ONE Flexicap Fund-Reg(IDCW Payout)",
  "INF579M01AR3": "360 ONE Flexicap Fund-Reg(IDCW)",
  "INF579M01902": "360 ONE Focused Fund(G)-Direct Plan",
  "INF579M01910": "360 ONE Focused Fund(IDCW)-Direct Plan",
  "INF579M01928": "360 ONE Focused Fund(IDCW-Reinv)-Direct Plan",
  "INF579M01878": "360 ONE Focused Fund-Reg(G)",
  "INF579M01886": "360 ONE Focused Fund-Reg(IDCW)",
  "INF579M01894": "360 ONE Focused Fund-Reg(IDCW-Reinv)",
  "INF579M01688": "360 ONE Liquid Fund(DD-IDCW)-Direct Plan",
  "INF579M01621": "360 ONE Liquid Fund(G)-Direct Plan",
  "INF579M01696": "360 ONE Liquid Fund(W-IDCW Reinv)-Direct Plan",
  "INF579M01639": "360 ONE Liquid Fund(W-IDCW)",
  "INF579M01563": "360 ONE Liquid Fund-Reg(DD-IDCW)",
  "INF579M01506": "360 ONE Liquid Fund-Reg(G)",
  "INF579M01571": "360 ONE Liquid Fund-Reg(W-IDCW Reinv)",
  "INF579M01514": "360 ONE Liquid Fund-Reg(W-IDCW)",
  "INF579M01BM2": "360 ONE Multi Asset Allocation Fund(G)-Direct Plan",
  "INF579M01BN0": "360 ONE Multi Asset Allocation Fund(IDCW Payout)-Direct Plan",
  "INF579M01BO8": "360 ONE Multi Asset Allocation Fund(IDCW)-Direct Plan",
  "INF579M01BJ8": "360 ONE Multi Asset Allocation Fund-Reg(G)",
  "INF579M01BK6": "360 ONE Multi Asset Allocation Fund-Reg(IDCW Payout)",
  "INF579M01BL4": "360 ONE Multi Asset Allocation Fund-Reg(IDCW)",
  "INF579M01BG4": "360 ONE Overnight Fund(G)-Direct Plan",
  "INF579M01BH2": "360 ONE Overnight Fund(IDCW Payout)-Direct Plan",
  "INF579M01BI0": "360 ONE Overnight Fund(IDCW)-Direct Plan",
  "INF579M01BD1": "360 ONE Overnight Fund-Reg(G)",
  "INF579M01BE9": "360 ONE Overnight Fund-Reg(IDCW Payout)",
  "INF579M01BF6": "360 ONE Overnight Fund-Reg(IDCW)",
  "INF579M01AI2": "360 ONE Quant Fund(G)-Direct Plan",
  "INF579M01AJ0": "360 ONE Quant Fund(IDCW Payout)-Direct Plan",
  "INF579M01AK8": "360 ONE Quant Fund(IDCW)-Direct Plan",
  "INF579M01AF8": "360 ONE Quant Fund-Reg(G)",
  "INF579M01AG6": "360 ONE Quant Fund-Reg(IDCW Payout)",
  "INF579M01AH4": "360 ONE Quant Fund-Reg(IDCW)",
  "INF084M01077": "Aditya Birla SL Aggressive Hybrid Omni FOF(G)",
  "INF084M01ET2": "Aditya Birla SL Aggressive Hybrid Omni FOF(G)-Direct Plan",
  "INF084M01085": "Aditya Birla SL Aggressive Hybrid Omni FOF(IDCW Payout)",
  "INF084M01EU0": "Aditya Birla SL Aggressive Hybrid Omni FOF(IDCW Payout)-Direct Plan",
  "INF084M01093": "Aditya Birla SL Aggressive Hybrid Omni FOF(IDCW)",
  "INF084M01EV8": "Aditya Birla SL Aggressive Hybrid Omni FOF(IDCW)-Direct Plan",
  "INF209K01264": "Aditya Birla SL Arbitrage Fund(G)",
  "INF209K01VP1": "Aditya Birla SL Arbitrage Fund(G)-Direct Plan",
  "INF209K01256": "Aditya Birla SL Arbitrage Fund(IDCW)",
  "INF209K01P80": "Aditya Birla SL Arbitrage Fund(IDCW)-Direct Plan",
  "INF209K01CI6": "Aditya Birla SL Arbitrage Fund(IDCW-Reinv)",
  "INF209K01VQ9": "Aditya Birla SL Arbitrage Fund(IDCW-Reinv)-Direct Plan",
  "INF084M01AB8": "Aditya Birla SL Balanced Advantage Fund(G)",
  "INF084M01DJ5": "Aditya Birla SL Balanced Advantage Fund(G)-Direct Plan",
  "INF084M01AD4": "Aditya Birla SL Balanced Advantage Fund(IDCW)",
  "INF084M01DL1": "Aditya Birla SL Balanced Advantage Fund(IDCW)-Direct Plan",
  "INF084M01AC6": "Aditya Birla SL Balanced Advantage Fund(IDCW-Payout)",
  "INF084M01DK3": "Aditya Birla SL Balanced Advantage Fund(IDCW-Payout)-Direct Plan",
  "INF209K014W1": "Aditya Birla SL Banking & Financial Services Fund(G)-Direct Plan",
  "INF209K013W3": "Aditya Birla SL Banking & Financial Services Fund(IDCW)-Direct Plan",
  "INF209K015W8": "Aditya Birla SL Banking & Financial Services Fund(IDCW-Reinv)-Direct Plan",
  "INF209K011W7": "Aditya Birla SL Banking & Financial Services Fund-Reg(G)",
  "INF209K010W9": "Aditya Birla SL Banking & Financial Services Fund-Reg(IDCW)",
  "INF209K012W5": "Aditya Birla SL Banking & Financial Services Fund-Reg(IDCW-Reinv)",
  "INF209K01LV0": "Aditya Birla SL Banking & PSU Debt Fund(G)",
  "INF209K01YN0": "Aditya Birla SL Banking & PSU Debt Fund(G)-Direct Plan",
  "INF209K01LX6": "Aditya Birla SL Banking & PSU Debt Fund(IDCW)",
  "INF209KA12Z1": "Aditya Birla SL Banking & PSU Debt Fund(IDCW)-Direct Plan",
  "INF209KA11Z3": "Aditya Birla SL Banking & PSU Debt Fund(IDCW-Reinv)",
  "INF209KA13Z9": "Aditya Birla SL Banking & PSU Debt Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01LU2": "Aditya Birla SL Banking & PSU Debt Fund(M-IDCW)",
  "INF209K01YM2": "Aditya Birla SL Banking & PSU Debt Fund(M-IDCW)-Direct Plan",
  "INF209K01LN7": "Aditya Birla SL Banking & PSU Debt Fund(Q-IDCW)",
  "INF209K01YO8": "Aditya Birla SL Banking & PSU Debt Fund(Q-IDCW)-Direct Plan",
  "INF209KC1589": "Aditya Birla SL BSE 500 Momentum 50 Index Fund(G)-Direct Plan",
  "INF209KC1597": "Aditya Birla SL BSE 500 Momentum 50 Index Fund(IDCW)-Direct Plan",
  "INF209KC1605": "Aditya Birla SL BSE 500 Momentum 50 Index Fund-Reg(G)",
  "INF209KC1654": "Aditya Birla SL BSE 500 Momentum 50 Index Fund-Reg(IDCW)",
  "INF209KC1613": "Aditya Birla SL BSE 500 Quality 50 Index Fund(G)-Direct Plan",
  "INF209KC1621": "Aditya Birla SL BSE 500 Quality 50 Index Fund(IDCW)-Direct Plan",
  "INF209KC1639": "Aditya Birla SL BSE 500 Quality 50 Index Fund-Reg(G)",
  "INF209KC1647": "Aditya Birla SL BSE 500 Quality 50 Index Fund-Reg(IDCW)",
  "INF209KC1332": "Aditya Birla SL BSE India Infrastructure Index Fund(G)-Direct Plan",
  "INF209KC1340": "Aditya Birla SL BSE India Infrastructure Index Fund(IDCW)-Direct Plan",
  "INF209KC1357": "Aditya Birla SL BSE India Infrastructure Index Fund-Reg(G)",
  "INF209KC1365": "Aditya Birla SL BSE India Infrastructure Index Fund-Reg(IDCW)",
  "INF209KB14D2": "Aditya Birla SL Business Cycle Fund(G)-Direct Plan",
  "INF209KB15D9": "Aditya Birla SL Business Cycle Fund(IDCW)-Direct Plan",
  "INF209KB12D6": "Aditya Birla SL Business Cycle Fund-Reg(G)",
  "INF209KB13D4": "Aditya Birla SL Business Cycle Fund-Reg(IDCW)",
  "INF209KC1373": "Aditya Birla SL Conglomerate Fund(G)-Direct Plan",
  "INF209KC1381": "Aditya Birla SL Conglomerate Fund(IDCW)-Direct Plan",
  "INF209KC1399": "Aditya Birla SL Conglomerate Fund-Reg(G)",
  "INF209KC1407": "Aditya Birla SL Conglomerate Fund-Reg(IDCW)",
  "INF209K01WC7": "Aditya Birla SL Consumption Fund(G)-Direct Plan",
  "INF209K01WD5": "Aditya Birla SL Consumption Fund(IDCW Reinvest)-Direct Plan",
  "INF209K01Q63": "Aditya Birla SL Consumption Fund(IDCW)-Direct Plan",
  "INF209K01447": "Aditya Birla SL Consumption Fund-Reg(G)",
  "INF209K01CR7": "Aditya Birla SL Consumption Fund-Reg(IDCW Reinvest)",
  "INF209K01439": "Aditya Birla SL Consumption Fund-Reg(IDCW)",
  "INF209K01785": "Aditya Birla SL Corp Bond Fund(G)",
  "INF209K01S38": "Aditya Birla SL Corp Bond Fund(G)-Direct Plan",
  "INF209KA1KS2": "Aditya Birla SL Corp Bond Fund(IDCW)",
  "INF209KA1KT0": "Aditya Birla SL Corp Bond Fund(IDCW)-Direct Plan",
  "INF209K01DL8": "Aditya Birla SL Corp Bond Fund(M-IDCW Reinv)",
  "INF209KA1KU8": "Aditya Birla SL Corp Bond Fund(M-IDCW Reinv)-Direct Plan",
  "INF209K01983": "Aditya Birla SL Corp Bond Fund(M-IDCW)",
  "INF209K01N90": "Aditya Birla SL Corp Bond Fund(M-IDCW)-Direct Plan",
  "INF209K01140": "Aditya Birla SL Digital India Fund(G)",
  "INF209K01VF2": "Aditya Birla SL Digital India Fund(G)-Direct Plan",
  "INF209K01132": "Aditya Birla SL Digital India Fund(IDCW)",
  "INF209K01P49": "Aditya Birla SL Digital India Fund(IDCW)-Direct Plan",
  "INF209K01CD7": "Aditya Birla SL Digital India Fund(IDCW-Reinv)",
  "INF209K01VE5": "Aditya Birla SL Digital India Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01405": "Aditya Birla SL Dividend Yield Fund(G)",
  "INF209K01WA1": "Aditya Birla SL Dividend Yield Fund(G)-Direct Plan",
  "INF209K01397": "Aditya Birla SL Dividend Yield Fund(IDCW)",
  "INF209K01Q55": "Aditya Birla SL Dividend Yield Fund(IDCW)-Direct Plan",
  "INF209K01CP1": "Aditya Birla SL Dividend Yield Fund(IDCW-Reinv)",
  "INF209K01WB9": "Aditya Birla SL Dividend Yield Fund(IDCW-Reinv)-Direct Plan",
  "INF084M01101": "Aditya Birla SL Dynamic Asset Allocation Omni FOF(G)",
  "INF084M01EW6": "Aditya Birla SL Dynamic Asset Allocation Omni FOF(G)-Direct Plan",
  "INF084M01119": "Aditya Birla SL Dynamic Asset Allocation Omni FOF(IDCW Payout)",
  "INF084M01127": "Aditya Birla SL Dynamic Asset Allocation Omni FOF(IDCW)",
  "INF084M01EY2": "Aditya Birla SL Dynamic Asset Allocation Omni FOF(IDCW)-Direct Plan",
  "INF209K01N82": "Aditya Birla SL Dynamic Bond Fund(G)-Direct Plan",
  "INF209KA1TX3": "Aditya Birla SL Dynamic Bond Fund(IDCW)-Direct Plan",
  "INF209KA1TY1": "Aditya Birla SL Dynamic Bond Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01R54": "Aditya Birla SL Dynamic Bond Fund(M-IDCW Reinv)-Direct Plan",
  "INF209K01R62": "Aditya Birla SL Dynamic Bond Fund(M-IDCW)-Direct Plan",
  "INF209K01R70": "Aditya Birla SL Dynamic Bond Fund(Q-IDCW Reinv)-Direct Plan",
  "INF209K01R88": "Aditya Birla SL Dynamic Bond Fund(Q-IDCW)-Direct Plan",
  "INF209K01JW2": "Aditya Birla SL Dynamic Bond Fund-DAP(G)",
  "INF209K01793": "Aditya Birla SL Dynamic Bond Fund-Reg(G)",
  "INF209KA1TV7": "Aditya Birla SL Dynamic Bond Fund-Reg(IDCW)",
  "INF209KA1TW5": "Aditya Birla SL Dynamic Bond Fund-Reg(IDCW)",
  "INF209K01DG8": "Aditya Birla SL Dynamic Bond Fund-Reg(M-IDCW Reinv)",
  "INF209K01801": "Aditya Birla SL Dynamic Bond Fund-Reg(M-IDCW)",
  "INF209K01DH6": "Aditya Birla SL Dynamic Bond Fund-Reg(Q-IDCW Reinv)",
  "INF209K01819": "Aditya Birla SL Dynamic Bond Fund-Reg(Q-IDCW)",
  "INF209K01108": "Aditya Birla SL ELSS Tax Saver Fund(G)",
  "INF209K01UN8": "Aditya Birla SL ELSS Tax Saver Fund(G)-Direct Plan",
  "INF209K01KL3": "Aditya Birla SL ELSS Tax Saver Fund(G)-LSP",
  "INF209K01CB1": "Aditya Birla SL ELSS Tax Saver Fund(IDCW Reinvest)",
  "INF209K01090": "Aditya Birla SL ELSS Tax Saver Fund(IDCW)",
  "INF209K01P23": "Aditya Birla SL ELSS Tax Saver Fund(IDCW)-Direct Plan",
  "INF209K01UM0": "Aditya Birla SL ELSS Tax Saver Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01BT5": "Aditya Birla SL Equity Hybrid '95 Fund(G)",
  "INF209K01ZC0": "Aditya Birla SL Equity Hybrid '95 Fund(G)-Direct Plan",
  "INF209K01BS7": "Aditya Birla SL Equity Hybrid '95 Fund(IDCW)",
  "INF209KA1LH3": "Aditya Birla SL Equity Hybrid '95 Fund(IDCW)-Direct Plan",
  "INF209K01EE1": "Aditya Birla SL Equity Hybrid '95 Fund(IDCW-Reinv)",
  "INF209K01ZB2": "Aditya Birla SL Equity Hybrid '95 Fund(IDCW-Reinv)-Direct Plan",
  "INF209KA1TP9": "Aditya Birla SL Equity Savings Fund(G)-Direct Plan",
  "INF209KA1TQ7": "Aditya Birla SL Equity Savings Fund(IDCW)-Direct Plan",
  "INF209KA1TR5": "Aditya Birla SL Equity Savings Fund(IDCW-Reinv)-Direct Plan",
  "INF209KA1TS3": "Aditya Birla SL Equity Savings Fund-Reg(G)",
  "INF209KA1TT1": "Aditya Birla SL Equity Savings Fund-Reg(IDCW)",
  "INF209KA1TU9": "Aditya Birla SL Equity Savings Fund-Reg(IDCW-Reinv)",
  "INF209KB1U76": "Aditya Birla SL ESG Integration Strategy Fund(G)-Direct Plan",
  "INF209KB1U84": "Aditya Birla SL ESG Integration Strategy Fund(IDCW)-Direct Plan",
  "INF209KB1U92": "Aditya Birla SL ESG Integration Strategy Fund(IDCW-Reinv)-Direct Plan",
  "INF209KB1U43": "Aditya Birla SL ESG Integration Strategy Fund-Reg(G)",
  "INF209KB1U50": "Aditya Birla SL ESG Integration Strategy Fund-Reg(IDCW)",
  "INF209KB1U68": "Aditya Birla SL ESG Integration Strategy Fund-Reg(IDCW-Reinv)",
  "INF209K01XX1": "Aditya Birla SL Flexi Cap Fund(G)-Direct Plan",
  "INF209KA1LE0": "Aditya Birla SL Flexi Cap Fund(IDCW)-Direct Plan",
  "INF209K01XY9": "Aditya Birla SL Flexi Cap Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01AJ8": "Aditya Birla SL Flexi Cap Fund-Reg(G)",
  "INF209K01DT1": "Aditya Birla SL Flexi Cap Fund-Reg(IDCW Reinvest)",
  "INF209K01AQ3": "Aditya Birla SL Flexi Cap Fund-Reg(IDCW)",
  "INF209KA1LN1": "Aditya Birla SL Floating Rate Fund(DD-IDCW)",
  "INF209K01UW9": "Aditya Birla SL Floating Rate Fund(DD-IDCW)-Direct Plan",
  "INF209K01MG9": "Aditya Birla SL Floating Rate Fund(G)",
  "INF209K01UX7": "Aditya Birla SL Floating Rate Fund(G)-Direct Plan",
  "INF209K01MH7": "Aditya Birla SL Floating Rate Fund(W-IDCW)",
  "INF209K01UY5": "Aditya Birla SL Floating Rate Fund(W-IDCW)-Direct Plan",
  "INF209K01462": "Aditya Birla SL Focused Fund(G)",
  "INF209K01WE3": "Aditya Birla SL Focused Fund(G)-Direct Plan",
  "INF209K01454": "Aditya Birla SL Focused Fund(IDCW)",
  "INF209K01Q71": "Aditya Birla SL Focused Fund(IDCW)-Direct Plan",
  "INF209K01CS5": "Aditya Birla SL Focused Fund(IDCW-Reinv)",
  "INF209K01WF0": "Aditya Birla SL Focused Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01AC3": "Aditya Birla SL G-Sec Fund(G)",
  "INF209K01XP7": "Aditya Birla SL G-Sec Fund(G)-Direct Plan",
  "INF209K01AD1": "Aditya Birla SL G-Sec Fund(G)-Instant Gain",
  "INF209K01XQ5": "Aditya Birla SL G-Sec Fund(G)-Instant Gain-Direct Plan",
  "INF209K01DP9": "Aditya Birla SL G-Sec Fund(Q-IDCW Reinv)",
  "INF209K01XR3": "Aditya Birla SL G-Sec Fund(Q-IDCW Reinv)-Direct Plan",
  "INF209K01AF6": "Aditya Birla SL G-Sec Fund(Q-IDCW)",
  "INF209KA1LC4": "Aditya Birla SL G-Sec Fund(Q-IDCW)-Direct Plan",
  "INF209K01579": "Aditya Birla SL Income Fund(G)",
  "INF209K01WY1": "Aditya Birla SL Income Fund(G)-Direct Plan",
  "INF209KA1WJ6": "Aditya Birla SL Income Fund(IDCW)",
  "INF209KA1WL2": "Aditya Birla SL Income Fund(IDCW)-Direct Plan",
  "INF209KA1WK4": "Aditya Birla SL Income Fund(IDCW-Reinv)",
  "INF209KA1WM0": "Aditya Birla SL Income Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01CY3": "Aditya Birla SL Income Fund(Q-IDCW Reinv)",
  "INF209K01WZ8": "Aditya Birla SL Income Fund(Q-IDCW Reinv)-Direct Plan",
  "INF209K01587": "Aditya Birla SL Income Fund(Q-IDCW)",
  "INF209K01R13": "Aditya Birla SL Income Fund(Q-IDCW)-Direct Plan",
  "INF084M01DP2": "Aditya Birla SL Income Plus Arbitrage Active FOF(G)-Direct Plan",
  "INF084M01DQ0": "Aditya Birla SL Income Plus Arbitrage Active FOF(IDCW Payout)-Direct Plan",
  "INF084M01DR8": "Aditya Birla SL Income Plus Arbitrage Active FOF(IDCW)-Direct Plan",
  "INF084M01AH5": "Aditya Birla SL Income Plus Arbitrage Active FOF-Reg(G)",
  "INF084M01AI3": "Aditya Birla SL Income Plus Arbitrage Active FOF-Reg(IDCW Payout)",
  "INF084M01AJ1": "Aditya Birla SL Income Plus Arbitrage Active FOF-Reg(IDCW)",
  "INF209K01504": "Aditya Birla SL Infrastructure Fund(G)",
  "INF209K01WH6": "Aditya Birla SL Infrastructure Fund(G)-Direct Plan",
  "INF209K01470": "Aditya Birla SL Infrastructure Fund(IDCW)",
  "INF209K01WG8": "Aditya Birla SL Infrastructure Fund(IDCW)-Direct Plan",
  "INF209K01CT3": "Aditya Birla SL Infrastructure Fund(IDCW-Reinv)",
  "INF209K01WI4": "Aditya Birla SL Infrastructure Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01520": "Aditya Birla SL Intl. Equity Fund(G)",
  "INF209K01WS3": "Aditya Birla SL Intl. Equity Fund(G)-Direct Plan",
  "INF209K01512": "Aditya Birla SL Intl. Equity Fund(IDCW)",
  "INF209K01Q89": "Aditya Birla SL Intl. Equity Fund(IDCW)-Direct Plan",
  "INF209K01CV9": "Aditya Birla SL Intl. Equity Fund(IDCW-Reinv)",
  "INF209K01VH8": "Aditya Birla SL Large & Mid Cap Fund(G)-Direct Plan",
  "INF209K01VI6": "Aditya Birla SL Large & Mid Cap Fund(IDCW Reinvest)-Direct Plan",
  "INF209K01VG0": "Aditya Birla SL Large & Mid Cap Fund(IDCW)-Direct Plan",
  "INF209K01165": "Aditya Birla SL Large & Mid Cap Fund-Reg(G)",
  "INF209K01CE5": "Aditya Birla SL Large & Mid Cap Fund-Reg(IDCW Reinvest)",
  "INF209K01157": "Aditya Birla SL Large & Mid Cap Fund-Reg(IDCW)",
  "INF209K01YY7": "Aditya Birla SL Large Cap Fund(G)-Direct Plan",
  "INF209K01YW1": "Aditya Birla SL Large Cap Fund(IDCW Reinvest)-Direct Plan",
  "INF209K01YX9": "Aditya Birla SL Large Cap Fund(IDCW)-Direct Plan",
  "INF209K01KI9": "Aditya Birla SL Large Cap Fund(Trigger Facility)-Reg(G)",
  "INF209K01BR9": "Aditya Birla SL Large Cap Fund-Reg(G)",
  "INF209K01EC5": "Aditya Birla SL Large Cap Fund-Reg(IDCW Reinvest)",
  "INF209K01BO6": "Aditya Birla SL Large Cap Fund-Reg(IDCW)",
  "INF209K01SQ5": "Aditya Birla SL Liquid Fund(DD-IDCW)",
  "INF209K01UZ2": "Aditya Birla SL Liquid Fund(DD-IDCW)-Direct Plan",
  "INF209K01RU9": "Aditya Birla SL Liquid Fund(G)",
  "INF209K01VA3": "Aditya Birla SL Liquid Fund(G)-Direct Plan",
  "INF209KA1LI1": "Aditya Birla SL Liquid Fund(IDCW)",
  "INF209K01VD7": "Aditya Birla SL Liquid Fund(IDCW)-Direct Plan",
  "INF209KA1LJ9": "Aditya Birla SL Liquid Fund(W-IDCW Reinv)",
  "INF209K01VB1": "Aditya Birla SL Liquid Fund(W-IDCW Reinv)-Direct Plan",
  "INF209KA1LK7": "Aditya Birla SL Liquid Fund(W-IDCW)",
  "INF209K01VC9": "Aditya Birla SL Liquid Fund(W-IDCW)-Direct Plan",
  "INF209KB17J2": "Aditya Birla SL Long Duration Fund(G)-Direct Plan",
  "INF209KB19J8": "Aditya Birla SL Long Duration Fund(IDCW Reinvest)-Direct Plan",
  "INF209KB18J0": "Aditya Birla SL Long Duration Fund(IDCW)-Direct Plan",
  "INF209KB14J9": "Aditya Birla SL Long Duration Fund-Reg(G)",
  "INF209KB16J4": "Aditya Birla SL Long Duration Fund-Reg(IDCW Reinvest)",
  "INF209KB15J6": "Aditya Birla SL Long Duration Fund-Reg(IDCW)",
  "INF209KA1LP6": "Aditya Birla SL Low Duration Fund(DD-IDCW)",
  "INF209K01XW3": "Aditya Birla SL Low Duration Fund(DD-IDCW)-Direct Plan",
  "INF209K01LQ0": "Aditya Birla SL Low Duration Fund(G)",
  "INF209K01XU7": "Aditya Birla SL Low Duration Fund(G)-Direct Plan",
  "INF209K01XV5": "Aditya Birla SL Low Duration Fund(W-IDCW Reinv)-Direct Plan",
  "INF209KA1LQ4": "Aditya Birla SL Low Duration Fund(W-IDCW)",
  "INF209K01XA9": "Aditya Birla SL Medium Term Plan(G)-Direct Plan",
  "INF209KA1KN3": "Aditya Birla SL Medium Term Plan(H-IDCW)-Direct Plan",
  "INF209KA1KO1": "Aditya Birla SL Medium Term Plan(IDCW)-Direct Plan",
  "INF209KA1KP8": "Aditya Birla SL Medium Term Plan(Q-IDCW)-Direct Plan",
  "INF209K01603": "Aditya Birla SL Medium Term Plan-Reg(G)",
  "INF209K01CZ0": "Aditya Birla SL Medium Term Plan-Reg(H-IDCW Reinv)",
  "INF209K01595": "Aditya Birla SL Medium Term Plan-Reg(H-IDCW)",
  "INF209K01611": "Aditya Birla SL Medium Term Plan-Reg(IDCW)",
  "INF209K01DA1": "Aditya Birla SL Medium Term Plan-Reg(IDCW-Reinv)",
  "INF209K01637": "Aditya Birla SL Medium Term Plan-Reg(Q-IDCW)",
  "INF209KA1YK0": "Aditya Birla SL Mfg. Equity Fund(G)-Direct Plan",
  "INF209KA1YL8": "Aditya Birla SL Mfg. Equity Fund(IDCW)-Direct Plan",
  "INF209KA1YM6": "Aditya Birla SL Mfg. Equity Fund(IDCW-Reinv)-Direct Plan",
  "INF209KA1YH6": "Aditya Birla SL Mfg. Equity Fund-Reg(G)",
  "INF209KA1YI4": "Aditya Birla SL Mfg. Equity Fund-Reg(IDCW)",
  "INF209KA1YJ2": "Aditya Birla SL Mfg. Equity Fund-Reg(IDCW-Reinv)",
  "INF209K01363": "Aditya Birla SL Midcap Fund(G)",
  "INF209K01Q30": "Aditya Birla SL Midcap Fund(G)-Direct Plan",
  "INF209K01355": "Aditya Birla SL Midcap Fund(IDCW)",
  "INF209K01Q22": "Aditya Birla SL Midcap Fund(IDCW)-Direct Plan",
  "INF209K01CN6": "Aditya Birla SL Midcap Fund(IDCW-Reinv)",
  "INF209K01Q48": "Aditya Birla SL Midcap Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01VT3": "Aditya Birla SL MNC Fund(G)-Direct Plan",
  "INF209K01Q06": "Aditya Birla SL MNC Fund(IDCW)-Direct Plan",
  "INF209K01VU1": "Aditya Birla SL MNC Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01322": "Aditya Birla SL MNC Fund-Reg(G)",
  "INF209K01314": "Aditya Birla SL MNC Fund-Reg(IDCW)",
  "INF209K01FL3": "Aditya Birla SL MNC Fund-Reg(IDCW-Reinv)",
  "INF209K01SZ6": "Aditya Birla SL Money Manager Fund(DD-IDCW)",
  "INF209K01UT5": "Aditya Birla SL Money Manager Fund(DD-IDCW)-Direct Plan",
  "INF209K01RV7": "Aditya Birla SL Money Manager Fund(G)",
  "INF209K01UU3": "Aditya Birla SL Money Manager Fund(G)-Direct Plan",
  "INF209K01UV1": "Aditya Birla SL Money Manager Fund(W-IDCW Reinv)-Direct Plan",
  "INF209K01SY9": "Aditya Birla SL Money Manager Fund(W-IDCW)",
  "INF209KA1LM3": "Aditya Birla SL Money Manager Fund(W-IDCW)-Direct Plan",
  "INF209KB15M0": "Aditya Birla SL Multi - Asset Passive FoF(G)-Direct Plan",
  "INF209KB17M6": "Aditya Birla SL Multi - Asset Passive FoF(IDCW Reinv)-Direct Plan",
  "INF209KB16M8": "Aditya Birla SL Multi - Asset Passive FoF(IDCW)-Direct Plan",
  "INF209KB12M7": "Aditya Birla SL Multi - Asset Passive FoF-Reg(G)",
  "INF209KB14M3": "Aditya Birla SL Multi - Asset Passive FoF-Reg(IDCW Reinvest)",
  "INF209KB13M5": "Aditya Birla SL Multi - Asset Passive FoF-Reg(IDCW)",
  "INF209KB15R9": "Aditya Birla SL Multi Asset Allocation Fund(G)-Direct Plan",
  "INF209KB17R5": "Aditya Birla SL Multi Asset Allocation Fund(IDCW Reinvest)-Direct Plan",
  "INF209KB16R7": "Aditya Birla SL Multi Asset Allocation Fund(IDCW)-Direct Plan",
  "INF209KB12R6": "Aditya Birla SL Multi Asset Allocation Fund-Reg(G)",
  "INF209KB14R2": "Aditya Birla SL Multi Asset Allocation Fund-Reg(IDCW Reinvest)",
  "INF209KB13R4": "Aditya Birla SL Multi Asset Allocation Fund-Reg(IDCW)",
  "INF084M01AE2": "Aditya Birla SL Multi-Asset Omni FOF(G)",
  "INF084M01DM9": "Aditya Birla SL Multi-Asset Omni FOF(G)-Direct Plan",
  "INF084M01AF9": "Aditya Birla SL Multi-Asset Omni FOF(IDCW Payout)",
  "INF084M01DN7": "Aditya Birla SL Multi-Asset Omni FOF(IDCW Payout)-Direct Plan",
  "INF084M01AG7": "Aditya Birla SL Multi-Asset Omni FOF(IDCW)",
  "INF084M01DO5": "Aditya Birla SL Multi-Asset Omni FOF(IDCW)-Direct Plan",
  "INF209KB1Y49": "Aditya Birla SL Multi-Cap Fund(G)-Direct Plan",
  "INF209KB1Y56": "Aditya Birla SL Multi-Cap Fund(IDCW)-Direct Plan",
  "INF209KB1Y23": "Aditya Birla SL Multi-Cap Fund-Reg(G)",
  "INF209KB1Y31": "Aditya Birla SL Multi-Cap Fund-Reg(IDCW)",
  "INF209KB1Z71": "Aditya Birla SL Nifty 50 Equal Weight Index Fund(G)-Direct Plan",
  "INF209KB1Z97": "Aditya Birla SL Nifty 50 Equal Weight Index Fund(IDCW Reinv)-Direct Plan",
  "INF209KB1Z89": "Aditya Birla SL Nifty 50 Equal Weight Index Fund(IDCW)-Direct Plan",
  "INF209KB1Z48": "Aditya Birla SL Nifty 50 Equal Weight Index Fund-Reg(G)",
  "INF209KB1Z63": "Aditya Birla SL Nifty 50 Equal Weight Index Fund-Reg(IDCW Reinvest)",
  "INF209KB1Z55": "Aditya Birla SL Nifty 50 Equal Weight Index Fund-Reg(IDCW)",
  "INF209K01VY3": "Aditya Birla SL Nifty 50 Index Fund(G)-Direct Plan",
  "INF209K01VX5": "Aditya Birla SL Nifty 50 Index Fund(IDCW)-Direct Plan",
  "INF209K01VZ0": "Aditya Birla SL Nifty 50 Index Fund(IDCW-Reinv)-Direct Plan",
  "INF209K01LB2": "Aditya Birla SL Nifty 50 Index Fund-Reg(G)",
  "INF209K01LA4": "Aditya Birla SL Nifty 50 Index Fund-Reg(IDCW)",
  "INF209K01LC0": "Aditya Birla SL Nifty 50 Index Fund-Reg(IDCW-Reinv)",
  "INF209KC1183": "Aditya Birla SL Nifty India Defence Index Fund(G)-Direct Plan",
  "INF209KC1191": "Aditya Birla SL Nifty India Defence Index Fund(IDCW)-Direct Plan",
  "INF209KC1159": "Aditya Birla SL Nifty India Defence Index Fund-Reg(G)",
  "INF209KC1167": "Aditya Birla SL Nifty India Defence Index Fund-Reg(IDCW)",
  "INF209KB1W74": "Aditya Birla SL Nifty Midcap 150 Index Fund(G)-Direct Plan",
  "INF209KB1W82": "Aditya Birla SL Nifty Midcap 150 Index Fund(IDCW)-Direct Plan",
  "INF209KB1W90": "Aditya Birla SL Nifty Midcap 150 Index Fund(IDCW-Reinv)-Direct Plan",
  "INF209KB1W41": "Aditya Birla SL Nifty Midcap 150 Index Fund-Reg(G)",
  "INF209KB1W66": "Aditya Birla SL Nifty Midcap 150 Index Fund-Reg(IDCW Reinv)",
  "INF209KB1W58": "Aditya Birla SL Nifty Midcap 150 Index Fund-Reg(IDCW)",
  "INF209KB10G3": "Aditya Birla SL Nifty Next 50 Index Fund(G)-Direct Plan",
  "INF209KB11G1": "Aditya Birla SL Nifty Next 50 Index Fund(IDCW)-Direct Plan",
  "INF209KB12G9": "Aditya Birla SL Nifty Next 50 Index Fund-Reg(G)",
  "INF209KB13G7": "Aditya Birla SL Nifty Next 50 Index Fund-Reg(IDCW)",
  "INF209KB1W17": "Aditya Birla SL Nifty Smallcap 50 Index Fund(G)-Direct Plan",
  "INF209KB1W33": "Aditya Birla SL Nifty Smallcap 50 Index Fund(IDCW Reinv)-Direct Plan",
  "INF209KB1W25": "Aditya Birla SL Nifty Smallcap 50 Index Fund(IDCW)-Direct Plan",
  "INF209KB1V83": "Aditya Birla SL Nifty Smallcap 50 Index Fund-Reg(G)",
  "INF209KB1W09": "Aditya Birla SL Nifty Smallcap 50 Index Fund-Reg(IDCW Reinvest)",
  "INF209KB1V91": "Aditya Birla SL Nifty Smallcap 50 Index Fund-Reg(IDCW)",
  "INF209KB1ZI0": "Aditya Birla SL Overnight Fund(DD-IDCW)-Direct Plan",
  "INF209KB1ZH2": "Aditya Birla SL Overnight Fund(G)-Direct Plan",
  "INF209KB1ZK6": "Aditya Birla SL Overnight Fund(M-IDCW Reinv)-Direct Plan",
  "INF209KB1ZL4": "Aditya Birla SL Overnight Fund(M-IDCW)-Direct Plan",
  "INF209KB1ZJ8": "Aditya Birla SL Overnight Fund(W-IDCW)-Direct Plan",
  "INF209KB1ZD1": "Aditya Birla SL Overnight Fund-Reg(DD-IDCW)",
  "INF209KB1ZC3": "Aditya Birla SL Overnight Fund-Reg(G)",
  "INF209KB1ZF6": "Aditya Birla SL Overnight Fund-Reg(M-IDCW Reinv)",
  "INF209KB1ZG4": "Aditya Birla SL Overnight Fund-Reg(M-IDCW)",
  "INF209KB1ZE9": "Aditya Birla SL Overnight Fund-Reg(W-IDCW)",
  "INF209KB1O25": "Aditya Birla SL Pharma & Healthcare Fund(G)-Direct Plan",
  "INF209KB1O33": "Aditya Birla SL Pharma & Healthcare Fund(IDCW)-Direct Plan",
  "INF209KB1O41": "Aditya Birla SL Pharma & Healthcare Fund(IDCW-Reinv)-Direct Plan",
  "INF209KB1N91": "Aditya Birla SL Pharma & Healthcare Fund-Reg(G)",
  "INF209KB1O09": "Aditya Birla SL Pharma & Healthcare Fund-Reg(IDCW)",
  "INF209KB1O17": "Aditya Birla SL Pharma & Healthcare Fund-Reg(IDCW-Reinv)",
  "INF209KB1O82": "Aditya Birla SL PSU Equity Fund(G)-Direct Plan",
  "INF209KB1O90": "Aditya Birla SL PSU Equity Fund(IDCW)-Direct Plan",
  "INF209KB1O66": "Aditya Birla SL PSU Equity Fund-Reg(G)",
  "INF209KB1O74": "Aditya Birla SL PSU Equity Fund-Reg(IDCW)",
  "INF209KC1118": "Aditya Birla SL Quant Fund(G)-Direct Plan",
  "INF209KC1126": "Aditya Birla SL Quant Fund(IDCW)-Direct Plan",
  "INF209KC1092": "Aditya Birla SL Quant Fund-Reg(G)",
  "INF209KC1100": "Aditya Birla SL Quant Fund-Reg(IDCW)",
  "INF209K01751": "Aditya Birla SL Regular Savings Fund(G)",
  "INF209K01XH4": "Aditya Birla SL Regular Savings Fund(G)-Direct Plan",
  "INF209K01DF0": "Aditya Birla SL Regular Savings Fund(M-IDCW Reinv)",
  "INF209K01XI2": "Aditya Birla SL Regular Savings Fund(M-IDCW Reinv)-Direct Plan",
  "INF209K01769": "Aditya Birla SL Regular Savings Fund(M-IDCW)",
  "INF209K01R47": "Aditya Birla SL Regular Savings Fund(M-IDCW)-Direct Plan",
  "INF209K01777": "Aditya Birla SL Regular Savings Fund(Payment)",
  "INF209K01XJ0": "Aditya Birla SL Regular Savings Fund(Payment)-Direct Plan",
  "INF209K01JT8": "Aditya Birla SL Savings Fund(DAP)",
  "INF209K01UQ1": "Aditya Birla SL Savings Fund(DD-IDCW)-Direct Plan",
  "INF209K01UR9": "Aditya Birla SL Savings Fund(G)-Direct Plan",
  "INF209K01US7": "Aditya Birla SL Savings Fund(W-IDCW)-Direct Plan",
  "INF209K01LY4": "Aditya Birla SL Savings Fund-Reg(DD-IDCW)",
  "INF209K01LZ1": "Aditya Birla SL Savings Fund-Reg(G)",
  "INF209K01MA2": "Aditya Birla SL Savings Fund-Reg(W-IDCW)",
  "INF209K01942": "Aditya Birla SL Short Term Fund(G)",
  "INF209K01XK8": "Aditya Birla SL Short Term Fund(G)-Direct Plan",
  "INF209K01975": "Aditya Birla SL Short Term Fund(IDCW)",
  "INF209K01R96": "Aditya Birla SL Short Term Fund(IDCW)-Direct Plan",
  "INF209K01DK0": "Aditya Birla SL Short Term Fund(IDCW-Reinv)",
  "INF209K01XL6": "Aditya Birla SL Short Term Fund(IDCW-Reinv)-Direct Plan",
  "INF209KA1KR4": "Aditya Birla SL Short Term Fund(Q-IDCW Reinv)-Direct Plan",
  "INF209K01BU3": "Aditya Birla SL Short Term Fund(Q-IDCW)",
  "INF209KA1KQ6": "Aditya Birla SL Short Term Fund(Q-IDCW)-Direct Plan",
  "INF209K01EN2": "Aditya Birla SL Small Cap Fund(G)",
  "INF209K01WN4": "Aditya Birla SL Small Cap Fund(G)-Direct Plan",
  "INF209K01EO0": "Aditya Birla SL Small Cap Fund(IDCW)",
  "INF209K01WM6": "Aditya Birla SL Small Cap Fund(IDCW)-Direct Plan",
  "INF209K01EP7": "Aditya Birla SL Small Cap Fund(IDCW-Reinv)",
  "INF209K01WO2": "Aditya Birla SL Small Cap Fund(IDCW-Reinv)-Direct Plan",
  "INF209KB1T79": "Aditya Birla SL Special Opp Fund(G)-Direct Plan",
  "INF209KB1T87": "Aditya Birla SL Special Opp Fund(IDCW)-Direct Plan",
  "INF209KB1T95": "Aditya Birla SL Special Opp Fund(IDCW-Reinv)-Direct Plan",
  "INF209KB1T46": "Aditya Birla SL Special Opp Fund-Reg(G)",
  "INF209KB1T53": "Aditya Birla SL Special Opp Fund-Reg(IDCW)",
  "INF209KB1T61": "Aditya Birla SL Special Opp Fund-Reg(IDCW-Reinv)",
  "INF209KB15X7": "Aditya Birla SL Transportation and Logistics Fund(G)-Direct Plan",
  "INF209KB16X5": "Aditya Birla SL Transportation and Logistics Fund(IDCW)-Direct Plan",
  "INF209KB17X3": "Aditya Birla SL Transportation and Logistics Fund-Reg(G)",
  "INF209KB18X1": "Aditya Birla SL Transportation and Logistics Fund-Reg(IDCW)",
  "INF209K01WQ7": "Aditya Birla SL Value Fund(G)-Direct Plan",
  "INF209K01WR5": "Aditya Birla SL Value Fund(IDCW Reinvest)-Direct Plan",
  "INF209K01WP9": "Aditya Birla SL Value Fund(IDCW)-Direct Plan",
  "INF209K01LF3": "Aditya Birla SL Value Fund-Reg(G)",
  "INF209K01LG1": "Aditya Birla SL Value Fund-Reg(IDCW Reinvest)",
  "INF209K01LE6": "Aditya Birla SL Value Fund-Reg(IDCW)",
};
export default group1;
