// Unique fund names only — for autocomplete / lookup
// 1494 funds

const MF_NAMES = [
  "360 ONE Balanced Hybrid Fund",
  "360 ONE Dynamic Bond Fund",
  "360 ONE ELSS Tax Saver Nifty 50 Index Fund",
  "360 ONE Flexicap Fund",
  "360 ONE Focused Equity Fund",
  "360 ONE Focused Fund",
  "360 ONE Liquid Fund",
  "360 ONE Multi Asset Allocation Fund",
  "360 ONE Overnight Fund",
  "360 ONE Quant Fund",
  "Aditya Birla SL Aggressive Hybrid Omni FOF",
  "Aditya Birla SL Arbitrage Fund",
  "Aditya Birla SL Balanced Advantage Fund",
  "Aditya Birla SL Banking & Financial Services Fund",
  "Aditya Birla SL Banking & PSU Debt",
  "Aditya Birla SL Banking & PSU Debt Fund",
  "Aditya Birla SL BSE 500 Momentum 50 Index Fund",
  "Aditya Birla SL BSE 500 Quality 50 Index Fund",
  "Aditya Birla SL BSE India Infrastructure Index Fund",
  "Aditya Birla SL BSE Sensex ETF",
  "Aditya Birla SL Business Cycle Fund",
  "Aditya Birla SL Conglomerate Fund",
  "Aditya Birla SL Consumption Fund",
  "Aditya Birla SL Corp Bond Fund",
  "Aditya Birla SL CRISIL IBX 60:40 SDL + AAA PSU",
  "Aditya Birla SL CRISIL IBX Gilt Apr 2029 Index Fund",
  "Aditya Birla SL Digital India Fund",
  "Aditya Birla SL Dividend Yield Fund",
  "Aditya Birla SL Dynamic Asset Allocation Omni FOF",
  "Aditya Birla SL Dynamic Bond Fund",
  "Aditya Birla SL ELSS Tax Saver Fund",
  "Aditya Birla SL Equity Advantage Fund",
  "Aditya Birla SL Equity Hybrid '95 Fund",
  "Aditya Birla SL Equity Savings Fund",
  "Aditya Birla SL ESG Integration Strategy Fund",
  "Aditya Birla SL Flexi Cap Fund",
  "Aditya Birla SL Floating Rate Fund",
  "Aditya Birla SL Focused Fund",
  "Aditya Birla SL G",
  "Aditya Birla SL Income Fund",
  "Aditya Birla SL Income Plus Arbitrage Active FOF",
  "Aditya Birla SL India GenNext Fund",
  "Aditya Birla SL Infrastructure Fund",
  "Aditya Birla SL Intl. Equity Fund",
  "Aditya Birla SL Large & Mid Cap Fund",
  "Aditya Birla SL Large Cap Fund",
  "Aditya Birla SL Liquid Fund",
  "Aditya Birla SL Long Duration Fund",
  "Aditya Birla SL Low Duration Fund",
  "Aditya Birla SL Medium Term Plan",
  "Aditya Birla SL Mfg. Equity Fund",
  "Aditya Birla SL Midcap Fund",
  "Aditya Birla SL MNC Fund",
  "Aditya Birla SL Money Manager Fund",
  "Aditya Birla SL Multi",
  "Aditya Birla SL Multi Asset Allocation Fund",
  "Aditya Birla SL Nifty 50 Equal Weight Index Fund",
  "Aditya Birla SL Nifty 50 ETF",
  "Aditya Birla SL Nifty 50 Index Fund",
  "Aditya Birla SL Nifty Bank ETF",
  "Aditya Birla SL Nifty India Defence Index Fund",
  "Aditya Birla SL Nifty Midcap 150 Index Fund",
  "Aditya Birla SL Nifty Next 50 Index Fund",
  "Aditya Birla SL Nifty SDL Apr 2027 Index Fund",
  "Aditya Birla SL Nifty SDL Plus PSU Bond Sep 2026 60:40 Index Fund",
  "Aditya Birla SL Nifty Smallcap 50 Index Fund",
  "Aditya Birla SL Overnight Fund",
  "Aditya Birla SL Pharma & Healthcare Fund",
  "Aditya Birla SL PSU Equity Fund",
  "Aditya Birla SL Pure Value Fund",
  "Aditya Birla SL Quant Fund",
  "Aditya Birla SL Regular Savings Fund",
  "Aditya Birla SL Savings",
  "Aditya Birla SL Savings Fund",
  "Aditya Birla SL Short Term Fund",
  "Aditya Birla SL Small Cap Fund",
  "Aditya Birla SL Special Opp Fund",
  "Aditya Birla SL Transportation and Logistics Fund",
  "Aditya Birla SL Value Fund",
  "Axis Aggressive Hybrid Fund",
  "Axis Arbitrage Fund",
  "Axis Balanced Advantage Fund",
  "Axis Banking & PSU Debt Fund",
  "Axis Bluechip Fund",
  "Axis BSE Sensex ETF",
  "Axis BSE Sensex Index Fund",
  "Axis Business Cycles Fund",
  "Axis Conservative Hybrid Fund",
  "Axis Consumption Fund",
  "Axis Corp Bond Fund",
  "Axis CRISIL IBX 70:30 CPSE Plus SDL April 2025 Index Fund",
  "Axis CRISIL IBX SDL May 2027 Index Fund",
  "Axis Dynamic Bond Fund",
  "Axis ELSS Tax Saver Fund",
  "Axis Equity Savings Fund",
  "Axis ESG Integration Strategy Fund",
  "Axis Flexi Cap Fund",
  "Axis Floater Fund",
  "Axis Focused Fund",
  "Axis Gilt Fund",
  "Axis Growth Opp Fund",
  "Axis Income Plus Arbitrage Active FOF",
  "Axis Income Plus Arbitrage Passive FOF",
  "Axis India Manufacturing Fund",
  "Axis Innovation Fund",
  "Axis Large & Mid Cap Fund",
  "Axis Large Cap Fund",
  "Axis Liquid",
  "Axis Liquid Fund",
  "Axis Long Duration Fund",
  "Axis Midcap Fund",
  "Axis Momentum Fund",
  "Axis Money Market Fund",
  "Axis Multi Asset Allocation Fund",
  "Axis Multi Factor Passive FoF",
  "Axis Multicap Fund",
  "Axis Nifty 100 Index Fund",
  "Axis NIFTY 50 ETF",
  "Axis Nifty 50 Index Fund",
  "Axis Nifty 500 Index Fund",
  "Axis Nifty AAA Bond Plus SDL Apr 2026 50:50 ETF",
  "Axis NIFTY Bank ETF",
  "Axis Nifty Bank Index Fund",
  "Axis NIFTY IT Index Fund",
  "Axis Nifty Midcap 50 Index Fund",
  "Axis Nifty Next 50 Index Fund",
  "Axis Nifty Smallcap 50 Index Fund",
  "Axis Nifty500 Momentum 50 Index Fund",
  "Axis Nifty500 Quality 50 Index Fund",
  "Axis Nifty500 Value 50 Index Fund",
  "Axis Overnight Fund",
  "Axis Quant Fund",
  "Axis Regular Savings Fund",
  "Axis Services Opportunities Fund",
  "Axis Short Duration Fund",
  "Axis Short Term Fund",
  "Axis Small Cap Fund",
  "Axis Strategic Bond Fund",
  "Axis Treasury Advantage",
  "Axis Treasury Advantage Fund",
  "Axis Ultra Short Duration Fund",
  "Axis Value Fund",
  "Bajaj Finserv Arbitrage Fund",
  "Bajaj Finserv Balanced Advantage Fund",
  "Bajaj Finserv Banking and PSU Fund",
  "Bajaj Finserv Consumption Fund",
  "Bajaj Finserv ELSS Tax Saver Fund",
  "Bajaj Finserv Equity Savings Fund",
  "Bajaj Finserv Flexi Cap Fund",
  "Bajaj Finserv Gilt Fund",
  "Bajaj Finserv Healthcare Fund",
  "Bajaj Finserv Large and Mid Cap Fund",
  "Bajaj Finserv Large Cap Fund",
  "Bajaj Finserv Liquid Fund",
  "Bajaj Finserv Money Market Fund",
  "Bajaj Finserv Multi Asset Allocation Fund",
  "Bajaj Finserv Multi Cap Fund",
  "Bajaj Finserv Nifty 50 ETF",
  "Bajaj Finserv Nifty Bank ETF",
  "Bajaj Finserv Overnight Fund",
  "Bajaj Finserv Small Cap Fund",
  "Bandhan Aggressive Hybrid Fund",
  "Bandhan Arbitrage Fund",
  "Bandhan Balanced Advantage Fund",
  "Bandhan Banking & PSU Debt Fund",
  "Bandhan Banking and PSU Fund",
  "Bandhan Bond Fund",
  "Bandhan BSE India Sector Leaders Index Fund",
  "Bandhan Business Cycle Fund",
  "Bandhan Conservative Hybrid Fund",
  "Bandhan Core Equity Fund",
  "Bandhan Corp Bond Fund",
  "Bandhan CRISIL IBX 90:10 SDL Plus Gilt",
  "Bandhan CRISIL IBX Gilt April 2028 Index Fund",
  "Bandhan CRISIL IBX Gilt June 2027 Index Fund",
  "Bandhan Dynamic Bond Fund",
  "Bandhan ELSS Tax Saver Fund",
  "Bandhan Equity Savings Fund",
  "Bandhan Financial Services Fund",
  "Bandhan Flexi Cap Fund",
  "Bandhan Floater Fund",
  "Bandhan Focused Equity Fund",
  "Bandhan Focused Fund",
  "Bandhan G",
  "Bandhan Gilt Fund",
  "Bandhan Gilt Fund with 10 year constant duration Fund",
  "Bandhan Healthcare Fund",
  "Bandhan Hybrid Equity Fund",
  "Bandhan Income Plus Arbitrage Active FOF",
  "Bandhan Infrastructure Fund",
  "Bandhan Innovation Fund",
  "Bandhan Large & Mid Cap Fund",
  "Bandhan Large Cap Fund",
  "Bandhan Liquid Fund",
  "Bandhan Long Duration Fund",
  "Bandhan Low Duration Fund",
  "Bandhan Medium Duration Fund",
  "Bandhan Medium to Long Duration Fund",
  "Bandhan Midcap Fund",
  "Bandhan Money Manager Fund",
  "Bandhan Money Market Fund",
  "Bandhan Multi",
  "Bandhan Multi Asset Allocation Fund",
  "Bandhan Multi Cap Fund",
  "Bandhan Nifty 100 Index Fund",
  "Bandhan Nifty 50 Index Fund",
  "Bandhan Nifty 500 Momentum 50 Index Fund",
  "Bandhan Nifty Alpha 50 Index Fund",
  "Bandhan Nifty IT Index Fund",
  "Bandhan Nifty Midcap 150 Index Fund",
  "Bandhan Nifty Next 50 Index Fund",
  "Bandhan Nifty Smallcap 250 Index Fund",
  "Bandhan Nifty Total Market Index Fund",
  "Bandhan Nifty100 Low Volatility 30 Index Fund",
  "Bandhan Nifty200 Momentum 30 Index Fund",
  "Bandhan Overnight Fund",
  "Bandhan Short Duration Fund",
  "Bandhan Small Cap Fund",
  "Bandhan Sterling Value Fund",
  "Bandhan Transportation and Logistics Fund",
  "Bandhan Ultra Short Duration Fund",
  "Bandhan Ultra Short Term Fund",
  "Bandhan Value Fund",
  "Bank of India Arbitrage Fund",
  "Bank of India Balanced Advantage Fund",
  "Bank of India Bluechip Fund",
  "Bank of India Business Cycle Fund",
  "Bank of India Conservative Hybrid Fund",
  "Bank of India Consumption Fund",
  "Bank of India ELSS Tax Saver",
  "Bank of India Flexi Cap Fund",
  "Bank of India Large & Mid Cap Equity Fund",
  "Bank of India Large & Mid Cap Fund",
  "Bank of India Large Cap Fund",
  "Bank of India Liquid Fund",
  "Bank of India Mfg & Infra Fund",
  "Bank of India Mid & Small Cap Equity & Debt Fund",
  "Bank of India Mid Cap Fund",
  "Bank of India Money Market Fund",
  "Bank of India Multi Asset Allocation Fund",
  "Bank of India Multi Cap Fund",
  "Bank of India Overnight Fund",
  "Bank of India Short Term Income Fund",
  "Bank of India Small Cap Fund",
  "Bank of India Ultra Short Duration Fund",
  "Baroda BNP Paribas Aggressive Hybrid Fund",
  "Baroda BNP Paribas Arbitrage Fund",
  "Baroda BNP Paribas Balanced Advantage Fund",
  "Baroda BNP Paribas Banking and Fin Serv Fund",
  "Baroda BNP Paribas Banking and PSU Bond Fund",
  "Baroda BNP Paribas Business Conglomerates Fund",
  "Baroda BNP Paribas Business Cycle Fund",
  "Baroda BNP Paribas Conservative Hybrid Fund",
  "Baroda BNP Paribas Corp Bond Fund",
  "Baroda BNP Paribas Dividend Yield Fund",
  "Baroda BNP Paribas Dynamic Bond Fund",
  "Baroda BNP Paribas ELSS Tax Saver Fund",
  "Baroda BNP Paribas Energy Opportunities Fund",
  "Baroda BNP Paribas Equity Savings Fund",
  "Baroda BNP Paribas Flexi Cap Fund",
  "Baroda BNP Paribas Focused Fund",
  "Baroda BNP Paribas Gilt Fund",
  "Baroda BNP Paribas Health and Wellness Fund",
  "Baroda BNP Paribas Income Plus Arbitrage Active FoF",
  "Baroda BNP Paribas India Consumption Fund",
  "Baroda BNP Paribas Innovation Fund",
  "Baroda BNP Paribas Large & Mid Cap Fund",
  "Baroda BNP Paribas Large Cap Fund",
  "Baroda BNP Paribas Liquid Fund",
  "Baroda BNP Paribas Low Duration Fund",
  "Baroda BNP Paribas Manufacturing Fund",
  "Baroda BNP Paribas Mid Cap Fund",
  "Baroda BNP Paribas Money Market Fund",
  "Baroda BNP Paribas Multi Asset Active FoF",
  "Baroda BNP Paribas Multi Asset Fund",
  "Baroda BNP Paribas Multi Cap Fund",
  "Baroda BNP Paribas Nifty 50 Index Fund",
  "Baroda BNP Paribas Nifty200 Momentum 30 Index Fund",
  "Baroda BNP Paribas Overnight Fund",
  "Baroda BNP Paribas Short Duration Fund",
  "Baroda BNP Paribas Small Cap Fund",
  "Baroda BNP Paribas Ultra Short Duration Fund",
  "Baroda BNP Paribas Value Fund",
  "Canara Rob Balanced Advantage Fund",
  "Canara Rob Banking and PSU Debt Fund",
  "Canara Rob Bluechip Equity Fund",
  "Canara Rob Conservative Hybrid Fund",
  "Canara Rob Consumer Trends Fund",
  "Canara Rob Corp Bond Fund",
  "Canara Rob Dynamic Bond Fund",
  "Canara Rob ELSS Tax Saver",
  "Canara Rob Emerg Equities Fund",
  "Canara Rob Equity Hybrid Fund",
  "Canara Rob Flexi Cap Fund",
  "Canara Rob Focused Equity Fund",
  "Canara Rob Focused Fund",
  "Canara Rob Gilt Fund",
  "Canara Rob Income Fund",
  "Canara Rob Infrastructure Fund",
  "Canara Rob Large and Mid Cap Fund",
  "Canara Rob Large Cap Fund",
  "Canara Rob Liquid",
  "Canara Rob Liquid Fund",
  "Canara Rob Manufacturing Fund",
  "Canara Rob Mid Cap Fund",
  "Canara Rob Multi Asset Allocation Fund",
  "Canara Rob Multi Cap Fund",
  "Canara Rob Overnight Fund",
  "Canara Rob Savings Fund",
  "Canara Rob Short Duration Fund",
  "Canara Rob Small Cap Fund",
  "Canara Rob Ultra Short Term Fund",
  "Canara Rob Value Fund",
  "DHFL Pramerica Balanced Advantage Fund",
  "DHFL Pramerica Hybrid Equity Fund",
  "DSP 10Y G",
  "DSP Aggressive Hybrid Fund",
  "DSP Arbitrage Fund",
  "DSP Banking & Financial Services Fund",
  "DSP Banking & PSU Debt Fund",
  "DSP Bond Fund",
  "DSP BSE Liquid Rate ETF",
  "DSP Business Cycle Fund",
  "DSP Corp Bond Fund",
  "DSP Dynamic Asset Allocation Fund",
  "DSP ELSS Tax Saver Fund",
  "DSP Equity Opportunities Fund",
  "DSP Equity Savings Fund",
  "DSP Flexi Cap Fund",
  "DSP Floater Fund",
  "DSP Focus Fund",
  "DSP Focused Fund",
  "DSP Gilt Fund",
  "DSP Healthcare Fund",
  "DSP Income Plus Arbitrage Omni FoF",
  "DSP India T.I.G.E.R Fund",
  "DSP Large & Mid Cap Fund",
  "DSP Large Cap Fund",
  "DSP Liquidity Fund",
  "DSP Low Duration Fund",
  "DSP Midcap Fund",
  "DSP Multi Asset Allocation Fund",
  "DSP Multicap Fund",
  "DSP Natural Res & New Energy Fund",
  "DSP NIFTY 1D Rate Liquid ETF",
  "DSP Nifty 50 Equal Weight ETF",
  "DSP Nifty 50 Equal Weight Index Fund",
  "DSP Nifty 50 ETF",
  "DSP NIFTY 50 Index Fund",
  "DSP Nifty Bank ETF",
  "DSP Nifty Bank Index Fund",
  "DSP Nifty IT Index Fund",
  "DSP Nifty Midcap 150 Quality 50 Index Fund",
  "DSP NIFTY Next 50 Index Fund",
  "DSP Nifty Private Bank ETF",
  "DSP Nifty Private Bank Index Fund",
  "DSP Nifty SDL Plus G",
  "DSP Nifty Smallcap250 Quality 50 Index Fund",
  "DSP Nifty Top 10 Equal Weight Index Fund",
  "DSP Nifty500 Flexicap Quality 30 Index Fund",
  "DSP Overnight Fund",
  "DSP Quant Fund",
  "DSP Regular Savings Fund",
  "DSP Savings Fund",
  "DSP Short Term Fund",
  "DSP Small Cap Fund",
  "DSP Strategic Bond Fund",
  "DSP Top 100 Equity Fund",
  "DSP Ultra Short Fund",
  "DSP Value Fund",
  "E delweiss CRISIL IBX 50:50 Gilt Plus SDL Short Duration Index Fund",
  "Edelweiss Aggressive Hybrid Fund",
  "Edelweiss Arbitrage Fund",
  "Edelweiss Balanced Advantage Fund",
  "Edelweiss Banking and PSU Debt Fund",
  "Edelweiss BSE Internet Economy Index Fund",
  "Edelweiss Business Cycle Fund",
  "Edelweiss Consumption Fund",
  "Edelweiss CRISIL IBX 50:50 Gilt Plus SDL April 2037 Index Fund",
  "Edelweiss CRISIL IBX 50:50 Gilt Plus SDL Short Duration Index Fund",
  "Edelweiss CRISIL PSU Plus SDL 50:50 Oct 2025 Index Fund",
  "Edelweiss ELSS Tax saver Fund",
  "Edelweiss Equity Savings Fund",
  "Edelweiss Flexi Cap Fund",
  "Edelweiss Focused Fund",
  "Edelweiss Government Securities Fund",
  "Edelweiss Income Plus Arbitrage Active FoF",
  "Edelweiss Large & Mid Cap Fund",
  "Edelweiss Large Cap Fund",
  "Edelweiss Liquid",
  "Edelweiss Liquid Fund",
  "Edelweiss Low Duration Fund",
  "Edelweiss Mid Cap Fund",
  "Edelweiss Money Market Fund",
  "Edelweiss MSCI India Domestic & World Healthcare 45 Index Fund",
  "Edelweiss Multi Asset Allocation Fund",
  "Edelweiss Multi Asset Omni FoF",
  "Edelweiss Multi Cap Fund",
  "Edelweiss Nifty 100 Quality 30 Index Fund",
  "Edelweiss Nifty 50 Index Fund",
  "Edelweiss Nifty Alpha Low Volatility 30 Index Fund",
  "Edelweiss NIFTY Large Mid Cap 250 Index Fund",
  "Edelweiss Nifty Midcap150 Momentum 50 Index Fund",
  "Edelweiss Nifty Next 50 Index Fund",
  "Edelweiss Nifty PSU Bond Plus SDL Apr 2026 50:50 Index Fund",
  "Edelweiss Nifty PSU Bond Plus SDL Apr 2027 50:50 Index Fund",
  "Edelweiss Nifty Smallcap 250 Index Fund",
  "Edelweiss Nifty500 Multicap Momentum Quality 50 Index Fund",
  "Edelweiss Overnight Fund",
  "Edelweiss Recently Listed IPO Fund",
  "Edelweiss Small Cap Fund",
  "Edelweiss Technology Fund",
  "Franklin Asian Equity Fund",
  "Franklin Build India Fund",
  "Franklin India Aggressive Hybrid Fund",
  "Franklin India Arbitrage Fund",
  "Franklin India Balanced Advantage Fund",
  "Franklin India Banking & PSU Debt Fund",
  "Franklin India Bluechip Fund",
  "Franklin India Conservative Hybrid Fund",
  "Franklin India Corp Debt Fund",
  "Franklin India Debt Hybrid Fund",
  "Franklin India Dividend Yield Fund",
  "Franklin India Dynamic Asset Allocation Active FOFs",
  "Franklin India ELSS Tax Saver Fund",
  "Franklin India Equity Advantage Fund",
  "Franklin India Equity Hybrid Fund",
  "Franklin India Equity Savings Fund",
  "Franklin India Flexi Cap Fund",
  "Franklin India Floating Rate Fund",
  "Franklin India Focused Equity Fund",
  "Franklin India G",
  "Franklin India Income Plus Arbitrage Active FoF",
  "Franklin India Large & Mid Cap Fund",
  "Franklin India Large Cap Fund",
  "Franklin India Liquid Fund",
  "Franklin India Long Duration Fund",
  "Franklin India Low Duration Fund",
  "Franklin India Medium to Long Duration Fund",
  "Franklin India Mid Cap Fund",
  "Franklin India Money Market Fund",
  "Franklin India Multi Asset Allocation Fund",
  "Franklin India Multi Cap Fund",
  "Franklin India NSE Nifty 50 Index Fund",
  "Franklin India Opportunities Fund",
  "Franklin India Overnight Fund",
  "Franklin India Prima Fund",
  "Franklin India Small Cap Fund",
  "Franklin India Smaller Cos Fund",
  "Franklin India Technology Fund",
  "Franklin India Ultra Short Duration Fund",
  "Groww Aggressive Hybrid Fund",
  "Groww Banking & Financial Services Fund",
  "Groww Dynamic Bond Fund",
  "Groww ELSS Tax Saver Fund",
  "Groww Gilt Fund",
  "Groww Largecap Fund",
  "Groww Liquid Fund",
  "Groww Money Market Fund",
  "Groww Multi Asset Allocation Fund",
  "Groww Multicap Fund",
  "Groww Nifty EV & New Age Automotive ETF",
  "Groww Nifty EV & New Age Automotive ETF FOF",
  "Groww Nifty India Defence ETF FOF",
  "Groww Nifty India Railways PSU Index Fund",
  "Groww Nifty Non",
  "Groww Nifty Smallcap 250 Index Fund",
  "Groww Nifty Total Market Index Fund",
  "Groww Short Duration Fund",
  "Groww Value Fund",
  "HDFC Arbitrage",
  "HDFC Arbitrage Fund",
  "HDFC Balanced Advantage Fund",
  "HDFC Banking & Financial Services Fund",
  "HDFC Banking and PSU Debt Fund",
  "HDFC BSE 500 Index Fund",
  "HDFC BSE India Sector Leaders Index Fund",
  "HDFC BSE Sensex ETF",
  "HDFC BSE Sensex Index Fund",
  "HDFC Business Cycle Fund",
  "HDFC Capital Builder Value Fund",
  "HDFC Corp Bond Fund",
  "HDFC Defence Fund",
  "HDFC Diversified Equity All Cap Active FOF",
  "HDFC Dividend Yield Fund",
  "HDFC Dynamic Debt Fund",
  "HDFC ELSS Tax saver",
  "HDFC Equity Savings Fund",
  "HDFC Flexi Cap Fund",
  "HDFC Floating Rate Debt Fund",
  "HDFC Focused 30 Fund",
  "HDFC Focused Fund",
  "HDFC Gilt Fund",
  "HDFC Housing Opp Fund",
  "HDFC Hybrid Debt Fund",
  "HDFC Hybrid Equity Fund",
  "HDFC Income Fund",
  "HDFC Income Plus Arbitrage Active FOF",
  "HDFC Infrastructure Fund",
  "HDFC Innovation Fund",
  "HDFC Large and Mid Cap Fund",
  "HDFC Large Cap Fund",
  "HDFC Liquid Fund",
  "HDFC Long Duration Debt Fund",
  "HDFC Low Duration Fund",
  "HDFC Manufacturing Fund",
  "HDFC Medium Term Debt Fund",
  "HDFC Mid",
  "HDFC Mid Cap Fund",
  "HDFC MNC Fund",
  "HDFC Money Market Fund",
  "HDFC Multi",
  "HDFC Multi Cap Fund",
  "HDFC NIFTY 100 Equal Weight Index Fund",
  "HDFC NIFTY 100 Index Fund",
  "HDFC Nifty 50 ETF",
  "HDFC Nifty 50 Index Fund",
  "HDFC NIFTY Bank ETF",
  "HDFC Nifty G",
  "HDFC NIFTY G",
  "HDFC Nifty India Digital Index Fund",
  "HDFC Nifty LargeMidcap 250 Index Fund",
  "HDFC NIFTY Midcap 150 Index Fund",
  "HDFC NIFTY Next 50 Index Fund",
  "HDFC NIFTY Private Bank ETF",
  "HDFC NIFTY Realty Index Fund",
  "HDFC NIFTY Smallcap 250 ETF",
  "HDFC NIFTY Smallcap 250 Index Fund",
  "HDFC Nifty Top 20 Equal Weight Index Fund",
  "HDFC NIFTY100 Low Volatility 30 Index Fund",
  "HDFC Nifty100 Quality 30 Index Fund",
  "HDFC NIFTY200 Momentum 30 Index Fund",
  "HDFC NIFTY50 Equal Weight Index Fund",
  "HDFC Nifty500 Multicap 50:25:25 Index Fund",
  "HDFC Non",
  "HDFC Overnight Fund",
  "HDFC Pharma and Healthcare Fund",
  "HDFC Short Term Debt Fund",
  "HDFC Small Cap Fund",
  "HDFC Technology Fund",
  "HDFC Transportation and Logistics Fund",
  "HDFC Ultra Short Term Fund",
  "HDFC Value Fund",
  "Helios Balanced Advantage Fund",
  "Helios Financial Services Fund",
  "Helios Flexi Cap Fund",
  "Helios Large & Mid Cap Fund",
  "Helios Mid Cap Fund",
  "Helios Overnight Fund",
  "Helios Small Cap Fund",
  "HSBC Aggressive Hybrid Active FOF",
  "HSBC Aggressive Hybrid Fund",
  "HSBC Arbitrage Fund",
  "HSBC Balanced Advantage Fund",
  "HSBC Banking and PSU Debt Fund",
  "HSBC Business Cycles Fund",
  "HSBC Conservative Hybrid Fund",
  "HSBC Consumption Fund",
  "HSBC Corporate Bond Fund",
  "HSBC CRISIL IBX 50:50 Gilt Plus SDL Apr 2028 Index Fund",
  "HSBC Dynamic Bond Fund",
  "HSBC ELSS Tax saver Fund",
  "HSBC Equity Savings Fund",
  "HSBC Financial Services Fund",
  "HSBC Flexi Cap Fund",
  "HSBC Focused Fund",
  "HSBC Gilt Fund",
  "HSBC Income Plus Arbitrage Active FOF",
  "HSBC India Export Opportunities Fund",
  "HSBC Infrastructure Fund",
  "HSBC Large & Mid Cap Fund",
  "HSBC Large Cap Fund",
  "HSBC Liquid Fund",
  "HSBC Low Duration Fund",
  "HSBC Medium Duration Fund",
  "HSBC Medium to Long Duration Fund Fund",
  "HSBC Midcap Fund",
  "HSBC Money Market Fund",
  "HSBC Multi Asset Active FOF",
  "HSBC Multi Asset Allocation Fund",
  "HSBC Multi Cap Fund",
  "HSBC Nifty 50 Index Fund",
  "HSBC Nifty Next 50 Index Fund",
  "HSBC Overnight Fund",
  "HSBC Short Duration Fund",
  "HSBC Small Cap Fund",
  "HSBC Tax Saver Equity Fund",
  "HSBC Ultra Short Duration Fund",
  "HSBC Value Fund",
  "ICICI Pru Active Momentum Fund",
  "ICICI Pru All Seasons Bond Fund",
  "ICICI Pru Balanced Advantage Fund",
  "ICICI Pru Banking & Fin Serv Fund",
  "ICICI Pru Banking & PSU Debt Fund",
  "ICICI Pru Bharat 22 FOF",
  "ICICI Pru Bharat Consumption Fund",
  "ICICI Pru Bluechip Fund",
  "ICICI Pru Bond Fund",
  "ICICI Pru BSE 500 ETF",
  "ICICI Pru BSE 500 ETF FOF",
  "ICICI Pru BSE Liquid Rate ETF",
  "ICICI Pru BSE Sensex ETF",
  "ICICI Pru BSE Sensex Index Fund",
  "ICICI Pru Business Cycle Fund",
  "ICICI Pru Commodities Fund",
  "ICICI Pru Conglomerate Fund",
  "ICICI Pru Constant Maturity Gilt Fund",
  "ICICI Pru Corp Bond Fund",
  "ICICI Pru Diversified Debt Strategy Active FOF",
  "ICICI Pru Diversified Equity All Cap Omni FOF",
  "ICICI Pru Dividend Yield Equity Fund",
  "ICICI Pru Dynamic Asset Allocation Active FOF",
  "ICICI Pru ELSS Tax Saver Fund",
  "ICICI Pru Energy Opportunities Fund",
  "ICICI Pru Equity",
  "ICICI Pru Equity & Debt Fund",
  "ICICI Pru Equity Minimum Variance Fund",
  "ICICI Pru Equity Savings Fund",
  "ICICI Pru ESG Exclusionary Strategy Fund",
  "ICICI Pru Exports & Services Fund",
  "ICICI Pru Flexicap Fund",
  "ICICI Pru Floating Interest Fund",
  "ICICI Pru FMCG Fund",
  "ICICI Pru Focused Equity Fund",
  "ICICI Pru Gilt Fund",
  "ICICI Pru Housing Opp Fund",
  "ICICI Pru Income plus Arbitrage Omni FOF",
  "ICICI Pru India Opp Fund",
  "ICICI Pru Infrastructure Fund",
  "ICICI Pru Innovation Fund",
  "ICICI Pru Large & Mid Cap Fund",
  "ICICI Pru Large Cap Fund",
  "ICICI Pru Liquid Fund",
  "ICICI Pru Long Term Bond Fund",
  "ICICI Pru Manufacturing Fund",
  "ICICI Pru Medium Term Bond Fund",
  "ICICI Pru Midcap Fund",
  "ICICI Pru MNC Fund",
  "ICICI Pru Money Market Fund",
  "ICICI Pru Multi",
  "ICICI Pru Multi Sector Passive FOF",
  "ICICI Pru Multicap Fund",
  "ICICI Pru NASDAQ 100 Index Fund",
  "ICICI Pru Nifty 10 yr Benchmark G",
  "ICICI Pru Nifty 100 ETF",
  "ICICI Pru Nifty 100 Low Volatility 30 ETF",
  "ICICI Pru Nifty 100 Low Volatility 30 ETF FOF",
  "ICICI Pru Nifty 200 Momentum 30 ETF",
  "ICICI Pru Nifty 200 Momentum 30 Index Fund",
  "ICICI Pru Nifty 200 Quality 30 ETF",
  "ICICI Pru Nifty 50 ETF",
  "ICICI Pru Nifty 50 Index Fund",
  "ICICI Pru Nifty 500 Index Fund",
  "ICICI Pru Nifty Alpha Low",
  "ICICI Pru Nifty Auto ETF",
  "ICICI Pru Nifty Auto Index Fund",
  "ICICI Pru Nifty Bank ETF",
  "ICICI Pru Nifty Bank Index Fund",
  "ICICI Pru Nifty EV & New Age Automotive ETF FOF",
  "ICICI Pru Nifty FMCG ETF",
  "ICICI Pru Nifty G",
  "ICICI Pru Nifty Healthcare ETF",
  "ICICI Pru Nifty Infrastructure ETF",
  "ICICI Pru Nifty IT ETF",
  "ICICI Pru Nifty IT Index Fund",
  "ICICI Pru Nifty LargeMidcap 250 Index Fund",
  "ICICI Pru Nifty Metal ETF",
  "ICICI Pru Nifty Midcap 150 ETF",
  "ICICI Pru Nifty Midcap 150 Index Fund",
  "ICICI Pru Nifty Next 50 ETF",
  "ICICI Pru Nifty Next 50 Index Fund",
  "ICICI Pru Nifty Oil & Gas ETF",
  "ICICI Pru Nifty Pharma Index Fund",
  "ICICI Pru Nifty Private Bank ETF",
  "ICICI Pru Nifty PSU Bond Plus SDL Sep 2027 40:60 Index Fund",
  "ICICI Pru Nifty SDL Dec 2028 Index Fund",
  "ICICI Pru Nifty SDL Sep 2027 Index Fund",
  "ICICI Pru Nifty Smallcap 250 Index Fund",
  "ICICI Pru Nifty Top 15 Equal Weight Index Fund",
  "ICICI Pru Nifty200 Quality 30 Index Fund",
  "ICICI Pru Nifty200 Value 30 Index Fund",
  "ICICI Pru Nifty50 Equal Weight Index Fund",
  "ICICI Pru Nifty50 Value 20 ETF",
  "ICICI Pru Nifty50 Value 20 Index Fund",
  "ICICI Pru Overnight fund",
  "ICICI Pru Overnight Fund",
  "ICICI Pru Passive Multi",
  "ICICI Pru Pharma Healthcare & Diagnostics",
  "ICICI Pru PSU Equity Fund",
  "ICICI Pru Quality Fund",
  "ICICI Pru Quant Fund",
  "ICICI Pru Regular Income Fund",
  "ICICI Pru Regular Savings Fund",
  "ICICI Pru Rural Opportunities Fund",
  "ICICI Pru Savings Fund",
  "ICICI Pru Short Term Fund",
  "ICICI Pru Smallcap Fund",
  "ICICI Pru Technology Fund",
  "ICICI Pru Thematic Advantage Fund",
  "ICICI Pru Transportation and Logistics Fund",
  "ICICI Pru Ultra Short Term Fund Fund",
  "ICICI Pru US Bluechip Equity Fund",
  "ICICI Pru Value Discovery Fund",
  "ICICI Pru Value Fund",
  "Invesco India Aggressive Hybrid Fund",
  "Invesco India Arbitrage Fund",
  "Invesco India Balanced Advantage Fund",
  "Invesco India Banking and PSU Fund",
  "Invesco India Business Cycle Fund",
  "Invesco India Consumption Fund",
  "Invesco India Contra Fund",
  "Invesco India Corporate Bond Fund",
  "Invesco India ELSS Tax Saver Fund",
  "Invesco India Equity Savings Fund",
  "Invesco India ESG Integration Strategy Fund",
  "Invesco India Financial Services Fund",
  "Invesco India Flexi Cap Fund",
  "Invesco India Focused Fund",
  "Invesco India Gilt Fund",
  "Invesco India Income Plus Arbitrage Active FoF",
  "Invesco India Infrastructure Fund",
  "Invesco India Large & Mid Cap Fund",
  "Invesco India Largecap Fund",
  "Invesco India Liquid",
  "Invesco India Liquid Fund",
  "Invesco India Low Duration Fund",
  "Invesco India Manufacturing Fund",
  "Invesco India Medium Duration Fund",
  "Invesco India Midcap Fund",
  "Invesco India Money Market Fund",
  "Invesco India Multi Asset Allocation Fund",
  "Invesco India Multicap Fund",
  "Invesco India Overnight Fund",
  "Invesco India PSU Equity Fund",
  "Invesco India Short Duration Fund",
  "Invesco India Smallcap Fund",
  "Invesco India Technology Fund",
  "Invesco India Ultra Short Duration Fund",
  "ITI Arbitrage Fund",
  "ITI Balanced Advantage Fund",
  "ITI Banking & Financial Services Fund",
  "ITI Banking & PSU Debt Fund",
  "ITI Bharat Consumption Fund",
  "ITI Dynamic Bond Fund",
  "ITI ELSS Tax Saver Fund",
  "ITI Flexi Cap Fund",
  "ITI Focused Equity Fund",
  "ITI Focused Fund",
  "ITI Large & Mid Cap Fund",
  "ITI Large Cap Fund",
  "ITI Liquid Fund",
  "ITI Mid Cap Fund",
  "ITI Multi",
  "ITI Overnight Fund",
  "ITI Pharma & Healthcare Fund",
  "ITI Small Cap Fund",
  "ITI Ultra Short Duration Fund",
  "ITI Value Fund",
  "JM Aggressive Hybrid Fund",
  "JM Arbitrage Fund",
  "JM Dynamic Bond Fund",
  "JM ELSS Tax Saver Fund",
  "JM Flexicap Fund",
  "JM Focused Fund",
  "JM Large & Mid Cap Fund",
  "JM Large Cap Fund",
  "JM Liquid Fund",
  "JM Low Duration Fund",
  "JM Medium to Long Duration Fund",
  "JM Midcap Fund",
  "JM Overnight Fund",
  "JM Short Duration Fund",
  "JM Small Cap Fund",
  "JM Value Fund",
  "Kotak Active Momentum Fund",
  "Kotak Aggressive Hybrid Fund",
  "Kotak Arbitrage Fund",
  "Kotak Balanced Advantage Fund",
  "Kotak Banking & Financial Services Fund",
  "Kotak Banking and PSU Debt Fund",
  "Kotak Bluechip Fund",
  "Kotak Bond Fund",
  "Kotak Bond Short Term Fund",
  "Kotak BSE PSU Index Fund",
  "Kotak Business Cycle Fund",
  "Kotak Consumption Fund",
  "Kotak Contra Fund",
  "Kotak Corporate Bond Fund",
  "Kotak Debt Hybrid Fund",
  "Kotak Dynamic Bond Fund",
  "Kotak ELSS Tax Saver Fund",
  "Kotak Emerging Equity Fund",
  "Kotak Energy Opportunities Fund",
  "Kotak Equity Arbitrage Fund",
  "Kotak Equity Hybrid Fund",
  "Kotak Equity Opp Fund",
  "Kotak Equity Savings Fund",
  "Kotak ESG Exclusionary Strategy Fund",
  "Kotak Flexicap Fund",
  "Kotak Floating Rate Fund",
  "Kotak Focused Equity Fund",
  "Kotak Focused Fund",
  "Kotak Gilt",
  "Kotak Gilt Fund",
  "Kotak Healthcare Fund",
  "Kotak Income Plus Arbitrage Omni FOF",
  "Kotak India EQ Contra Fund",
  "Kotak Infra & Eco Reform Fund",
  "Kotak Large & Midcap Fund",
  "Kotak Large Cap Fund",
  "Kotak Liquid Fund",
  "Kotak Long Duration Fund",
  "Kotak Low Duration Fund",
  "Kotak Manufacture in India Fund",
  "Kotak Medium Term Fund",
  "Kotak Midcap Fund",
  "Kotak MNC Fund",
  "Kotak Money Market Fund",
  "Kotak Multi Asset Allocation Fund",
  "Kotak Multi Asset Omni FOF",
  "Kotak Multicap Fund",
  "Kotak Nifty 100 Equal Weight Index Fund",
  "Kotak Nifty 100 Low Volatility 30 ETF",
  "Kotak NIFTY 100 Low Volatility 30 Index Fund",
  "Kotak Nifty 1D Rate Liquid ETF",
  "Kotak Nifty 200 Momentum 30 Index Fund",
  "Kotak Nifty 50 Equal Weight Index Fund",
  "Kotak Nifty 50 ETF",
  "Kotak Nifty 50 Index Fund",
  "Kotak Nifty 50 Value 20 ETF",
  "Kotak Nifty Commodities Index Fund",
  "Kotak Nifty Financial Services Ex",
  "Kotak Nifty India Tourism Index Fund",
  "Kotak Nifty IT ETF",
  "Kotak NIFTY Midcap 150 Momentum 50 Index Fund",
  "Kotak NIFTY Midcap 50 Index Fund",
  "Kotak Nifty Next 50 Index Fund",
  "Kotak Nifty PSU Bank ETF",
  "Kotak Nifty SDL Apr 2027 Top 12 Equal Weight Index Fund",
  "Kotak Nifty SDL Apr 2032 Top 12 Equal Weight Index Fund",
  "Kotak Nifty SDL Plus AAA PSU Bond Jul 2028 60:40 Index Fund",
  "Kotak Nifty Smallcap 250 Index Fund",
  "Kotak Nifty Smallcap 50 Index Fund",
  "Kotak Nifty Top 10 Equal Weight Index Fund",
  "Kotak Overnight Fund",
  "Kotak Pioneer Fund",
  "Kotak Quant Fund",
  "Kotak Rural Opportunities Fund",
  "Kotak Savings Fund",
  "Kotak Small Cap Fund",
  "Kotak Special Opportunities Fund",
  "Kotak Technology Fund",
  "Kotak Transportation & Logistics Fund",
  "LIC MF Aggressive Hybrid Fund",
  "LIC MF Arbitrage Fund",
  "LIC MF Balanced Advantage Fund",
  "LIC MF Banking & Financial Services Fund",
  "LIC MF Banking & PSU Fund",
  "LIC MF BSE Sensex ETF",
  "LIC MF BSE Sensex Index Fund",
  "LIC MF Conservative Hybrid Fund",
  "LIC MF Consumption Fund",
  "LIC MF Dividend Yield Fund",
  "LIC MF ELSS Tax Saver",
  "LIC MF Equity Savings Fund",
  "LIC MF Flexi Cap Fund",
  "LIC MF Focused Fund",
  "LIC MF Gilt Fund",
  "LIC MF Healthcare Fund",
  "LIC MF Infra Fund",
  "LIC MF Large & Midcap Fund",
  "LIC MF Large Cap Fund",
  "LIC MF Liquid Fund",
  "LIC MF Low Duration Fund",
  "LIC MF Manufacturing Fund",
  "LIC MF Medium to Long Duration Fund",
  "LIC MF Midcap Fund",
  "LIC MF Money Market Fund",
  "LIC MF Multi Asset Allocation Fund",
  "LIC MF Multi Cap Fund",
  "LIC MF Nifty 100 ETF",
  "LIC MF Nifty 50 ETF",
  "LIC MF Nifty 50 Index Fund",
  "LIC MF Nifty 8",
  "LIC MF Nifty Next 50 Index Fund",
  "LIC MF Overnight Fund",
  "LIC MF Short Duration Fund",
  "LIC MF Small Cap Fund",
  "LIC MF Ultra Short Duration Fund",
  "LIC MF Value Fund",
  "Mahindra Manulife Aggressive Hybrid Fund",
  "Mahindra Manulife Arbitrage Fund",
  "Mahindra Manulife Balanced Advantage Fund",
  "Mahindra Manulife Banking & Financial Services Fund",
  "Mahindra Manulife Business Cycle Fund",
  "Mahindra Manulife Consumption Fund",
  "Mahindra Manulife Dynamic Bond Fund",
  "Mahindra Manulife ELSS Tax Saver Fund",
  "Mahindra Manulife Equity Savings Fund",
  "Mahindra Manulife Flexi Cap Fund",
  "Mahindra Manulife Focused Fund",
  "Mahindra Manulife Large & Mid Cap Fund",
  "Mahindra Manulife Large Cap Fund",
  "Mahindra Manulife Liquid Fund",
  "Mahindra Manulife Low Duration Fund",
  "Mahindra Manulife Manufacturing Fund",
  "Mahindra Manulife Mid Cap Fund",
  "Mahindra Manulife Multi Asset Allocation Fund",
  "Mahindra Manulife Multi Cap Fund",
  "Mahindra Manulife Overnight Fund",
  "Mahindra Manulife Short Duration Fund",
  "Mahindra Manulife Small Cap Fund",
  "Mahindra Manulife Ultra Short Duration Fund",
  "Mahindra Manulife Value Fund",
  "Mirae Asset Aggressive Hybrid Fund",
  "Mirae Asset Arbitrage Fund",
  "Mirae Asset Balanced Advantage Fund",
  "Mirae Asset Banking and Financial Services Fund",
  "Mirae Asset Banking and PSU Fund",
  "Mirae Asset Corp Bond Fund",
  "Mirae Asset Diversified Equity Allocator Passive FOF",
  "Mirae Asset Dynamic Bond Fund",
  "Mirae Asset ELSS Tax Saver Fund",
  "Mirae Asset Equity Savings Fund",
  "Mirae Asset Flexi Cap Fund",
  "Mirae Asset Focused Fund",
  "Mirae Asset Great Consumer Fund",
  "Mirae Asset Healthcare Fund",
  "Mirae Asset Large & Midcap Fund",
  "Mirae Asset Large Cap Fund",
  "Mirae Asset Liquid Fund",
  "Mirae Asset Long Duration Fund",
  "Mirae Asset Low Duration Fund",
  "Mirae Asset Midcap Fund",
  "Mirae Asset Money Market Fund",
  "Mirae Asset Multi Asset Allocation Fund",
  "Mirae Asset Multicap Fund",
  "Mirae Asset Nifty 100 ESG Sector Leaders ETF",
  "Mirae Asset Nifty 100 ESG Sector Leaders FoF",
  "Mirae Asset Nifty 200 Alpha 30 ETF",
  "Mirae Asset Nifty 50 ETF",
  "Mirae Asset Nifty 50 Index Fund",
  "Mirae Asset Nifty India Manufacturing ETF FoF",
  "Mirae Asset Nifty IT ETF",
  "Mirae Asset Nifty LargeMidcap 250 Index Fund",
  "Mirae Asset Nifty Midcap 150 ETF",
  "Mirae Asset Nifty MidSmallcap400 Momentum Quality 100 ETF FoF",
  "Mirae Asset Nifty Next 50 ETF",
  "Mirae Asset Nifty SDL Jun 2027 Index Fund",
  "Mirae Asset Nifty Smallcap 250 Momentum Quality 100 ETF",
  "Mirae Asset Nifty Smallcap 250 Momentum Quality 100 ETF FoF",
  "Mirae Asset Nifty Total Market Index Fund",
  "Mirae Asset Nifty200 Alpha 30 ETF FoF",
  "Mirae Asset Overnight Fund",
  "Mirae Asset Short Duration Fund",
  "Mirae Asset Small Cap Fund",
  "Mirae Asset Ultra Short Duration Fund",
  "Motilal Oswal 5 Year G",
  "Motilal Oswal Active Momentum Fund",
  "Motilal Oswal Arbitrage Fund",
  "Motilal Oswal Asset Allocation Passive FoF",
  "Motilal Oswal Balanced Advantage Fund",
  "Motilal Oswal BSE 1000 Index Fund",
  "Motilal Oswal BSE Enhanced Value ETF",
  "Motilal Oswal BSE Enhanced Value Index Fund",
  "Motilal Oswal BSE Financials ex Bank 30 Index Fund",
  "Motilal Oswal BSE Low Volatility Index Fund",
  "Motilal Oswal BSE Quality Index Fund",
  "Motilal Oswal Business Cycle Fund",
  "Motilal Oswal Consumption Fund",
  "Motilal Oswal Digital India Fund",
  "Motilal Oswal ELSS Tax Saver Fund",
  "Motilal Oswal Flexi Cap Fund",
  "Motilal Oswal Focused Fund",
  "Motilal Oswal Infrastructure Fund",
  "Motilal Oswal Innovation Opportunities Fund",
  "Motilal Oswal Large & Midcap Fund",
  "Motilal Oswal Large Cap Fund",
  "Motilal Oswal Liquid Fund",
  "Motilal Oswal Manufacturing Fund",
  "Motilal Oswal Midcap Fund",
  "Motilal Oswal Multi Asset Fund",
  "Motilal Oswal Multi Cap Fund",
  "Motilal Oswal Nifty 200 Momentum 30 ETF",
  "Motilal Oswal Nifty 200 Momentum 30 Index Fund",
  "Motilal Oswal Nifty 50 Index Fund",
  "Motilal Oswal Nifty 500 ETF",
  "Motilal Oswal Nifty 500 Index Fund",
  "Motilal Oswal Nifty 500 Momentum 50 Index Fund",
  "Motilal Oswal Nifty Bank Index Fund",
  "Motilal Oswal Nifty Capital Market Index Fund",
  "Motilal Oswal Nifty India Defence Index Fund",
  "Motilal Oswal Nifty Microcap 250 Index Fund",
  "Motilal Oswal Nifty Midcap 150 Index Fund",
  "Motilal Oswal Nifty MidSmall Financial Services Index Fund",
  "Motilal Oswal Nifty MidSmall Healthcare Index Fund",
  "Motilal Oswal Nifty MidSmall India Consumption Index Fund",
  "Motilal Oswal Nifty MidSmall IT and Telecom Index Fund",
  "Motilal Oswal Nifty Next 50 Index Fund",
  "Motilal Oswal Nifty Smallcap 250 Index Fund",
  "Motilal Oswal Quant Fund",
  "Motilal Oswal S&P 500 Index Fund",
  "Motilal Oswal Services Fund",
  "Motilal Oswal Small Cap Fund",
  "Motilal Oswal Special Opportunities Fund",
  "Motilal Oswal Ultra Short Term Fund",
  "Navi Aggressive Hybrid Fund",
  "Navi BSE Sensex Index Fund",
  "Navi ELSS Tax Saver Fund",
  "Navi ELSS Tax Saver Nifty 50 Index Fund",
  "Navi Flexi Cap Fund",
  "Navi Large & Midcap Fund",
  "Navi Liquid Fund",
  "Navi Nifty 50 Index Fund",
  "Navi Nifty 500 Multicap 50:25:25 Index Fund",
  "Navi Nifty Bank Index Fund",
  "Navi Nifty India Manufacturing Index Fund",
  "Navi Nifty IT Index Fund",
  "Navi Nifty Midcap 150 Index Fund",
  "Navi Nifty Next 50 Index Fund",
  "Navi Nifty Smallcap250 Momentum Quality 100 Index Fund",
  "Nippon India Active Momentum Fund",
  "Nippon India Aggressive Hybrid Fund",
  "Nippon India Arbitrage Fund",
  "Nippon India Balanced Advantage Fund",
  "Nippon India Banking & Financial Services Fund",
  "Nippon India Banking & PSU Debt Fund",
  "Nippon India Banking and PSU Fund",
  "Nippon India BSE Sensex Next 30 Index Fund",
  "Nippon India Conservative Hybrid Fund",
  "Nippon India Consumption Fund",
  "Nippon India Corp Bond Fund",
  "Nippon India Diversified Equity Flexicap Passive FoF",
  "Nippon India Dynamic Bond Fund",
  "Nippon India ELSS Tax Saver Fund",
  "Nippon India Equity Hybrid Fund",
  "Nippon India Equity Savings Fund",
  "Nippon India ETF Nifty 1D Rate Liquid BeES",
  "Nippon India ETF Nifty 8",
  "Nippon India ETF Nifty Midcap 150",
  "Nippon India ETF Nifty Next 50 Junior BeES",
  "Nippon India ETF Nifty PSU Bank BeES",
  "Nippon India ETF Nifty SDL Apr 2026 Top 20 Equal Weight",
  "Nippon India Flexi Cap Fund",
  "Nippon India Floater Fund",
  "Nippon India Floating Rate Fund",
  "Nippon India Focused Equity Fund",
  "Nippon India Focused Fund",
  "Nippon India Gilt Fund",
  "Nippon India Gilt Securities",
  "Nippon India Gilt Securities Fund",
  "Nippon India Growth Fund",
  "Nippon India Growth Mid Cap Fund",
  "Nippon India Hybrid Bond Fund",
  "Nippon India Income Plus Arbitrage Active FoF",
  "Nippon India Index Fund",
  "Nippon India Innovation Fund",
  "Nippon India Japan Equity Fund",
  "Nippon India Large Cap Fund",
  "Nippon India Liquid Fund",
  "Nippon India Low Duration Fund",
  "Nippon India Medium Duration Fund",
  "Nippon India Medium to Long Duration Fund",
  "Nippon India MNC Fund",
  "Nippon India Money Market Fund",
  "Nippon India Multi",
  "Nippon India Multi Asset Allocation Fund",
  "Nippon India Multi Cap Fund",
  "Nippon India Nifty 50 Value 20 Index Fund",
  "Nippon India Nifty 500 Equal Weight Index Fund",
  "Nippon India Nifty 500 Momentum 50 Index Fund",
  "Nippon India Nifty 500 Quality 50 Index Fund",
  "Nippon India Nifty AAA CPSE Bond Plus SDL",
  "Nippon India Nifty Alpha Low Volatility 30 Index Fund",
  "Nippon India Nifty Auto ETF",
  "Nippon India Nifty Auto Index Fund",
  "Nippon India Nifty Bank Index Fund",
  "Nippon India Nifty G",
  "Nippon India Nifty India Manufacturing Index Fund",
  "Nippon India Nifty IT Index Fund",
  "Nippon India Nifty Midcap 150 Index Fund",
  "Nippon India Nifty Next 50 Junior BeES FoF",
  "Nippon India Nifty Pharma ETF",
  "Nippon India Nifty Realty Index Fund",
  "Nippon India Nifty Smallcap 250 Index Fund",
  "Nippon India Nivesh Lakshya Fund",
  "Nippon India Nivesh Lakshya Long Duration Fund",
  "Nippon India Overnight Fund",
  "Nippon India Pharma Fund",
  "Nippon India Power & Infra Fund",
  "Nippon India Quant Fund",
  "Nippon India Short Duration Fund",
  "Nippon India Short Term Fund",
  "Nippon India Small Cap Fund",
  "Nippon India Taiwan Equity Fund",
  "Nippon India Ultra Short Duration Fund",
  "Nippon India US Equity Opp Fund",
  "Nippon India Value Fund",
  "Nippon India Vision Fund",
  "Nippon India Vision Large & Mid Cap Fund",
  "NJ Arbitrage Fund",
  "NJ Balanced Advantage Fund",
  "NJ ELSS Tax Saver Scheme",
  "NJ Flexi Cap Fund",
  "NJ Overnight Fund",
  "Old Bridge Arbitrage Fund",
  "Old Bridge Focused Fund",
  "Parag Parikh Arbitrage Fund",
  "Parag Parikh Conservative Hybrid Fund",
  "Parag Parikh Dynamic Asset Allocation Fund",
  "Parag Parikh ELSS Tax Saver Fund",
  "Parag Parikh Flexi Cap Fund",
  "Parag Parikh Liquid Fund",
  "PGIM India Aggressive Hybrid Equity Fund",
  "PGIM India Arbitrage Fund",
  "PGIM India Balanced Advantage Fund",
  "PGIM India Corp Bond Fund",
  "PGIM India Dynamic Bond Fund",
  "PGIM India ELSS Tax Saver Fund",
  "PGIM India Equity Savings Fund",
  "PGIM India Flexi Cap Fund",
  "PGIM India Gilt Fund",
  "PGIM India Healthcare Fund",
  "PGIM India Hybrid Equity Fund",
  "PGIM India Large and Mid Cap Fund",
  "PGIM India Large Cap Fund",
  "PGIM India Liquid Fund",
  "PGIM India Midcap Fund",
  "PGIM India Midcap Opp Fund",
  "PGIM India Money Market Fund",
  "PGIM India Multi Asset Allocation Fund",
  "PGIM India Multi Cap Fund",
  "PGIM India Overnight Fund",
  "PGIM India Small Cap Fund",
  "PGIM India Ultra Short Duration Fund",
  "Quant Aggressive Hybrid Fund",
  "Quant Arbitrage Fund",
  "Quant BFSI Fund",
  "Quant Business Cycle Fund",
  "Quant Commodities Fund",
  "Quant Consumption Fund",
  "Quant Dynamic Asset Allocation Fund",
  "Quant ELSS Tax Saver Fund",
  "Quant Equity Savings Fund",
  "Quant ESG Integration Strategy Fund",
  "Quant Flexi Cap Fund",
  "Quant Focused Fund",
  "Quant Gilt Fund",
  "Quant Healthcare Fund",
  "Quant Infrastructure Fund",
  "Quant Large & Mid Cap Fund",
  "Quant Large Cap Fund",
  "Quant Liquid Plan",
  "Quant Manufacturing Fund",
  "Quant Mid Cap Fund",
  "Quant Momentum Fund",
  "Quant Multi Asset Allocation Fund",
  "Quant Multi Asset Fund",
  "Quant Multi Cap Fund",
  "Quant Overnight Fund",
  "Quant PSU Fund",
  "Quant Quantamental Fund",
  "Quant Small Cap Fund",
  "Quant Teck Fund",
  "Quant Value Fund",
  "Quantum Diversified Equity All Cap Active FOF",
  "Quantum Dynamic Bond Fund",
  "Quantum ELSS Tax Saver Fund",
  "Quantum ESG Best In Class Strategy Fund",
  "Quantum Ethical Fund",
  "Quantum Liquid Fund",
  "Quantum Long Term Equity Value Fund",
  "Quantum Multi Asset Active FoF",
  "Quantum Nifty 50 ETF FoF",
  "Quantum Small Cap Fund",
  "Quantum Value Fund",
  "Samco Active Momentum Fund",
  "Samco Arbitrage Fund",
  "Samco Dynamic Asset Allocation Fund",
  "Samco ELSS Tax Saver Fund",
  "Samco Flexi Cap Fund",
  "Samco Large & Mid Cap Fund",
  "Samco Large Cap Fund",
  "Samco Multi Asset Allocation Fund",
  "Samco Multi Cap Fund",
  "Samco Overnight Fund",
  "Samco Special Opportunities Fund",
  "SBI Arbitrage Opportunities Fund",
  "SBI Automotive Opportunities Fund",
  "SBI Balanced Advantage Fund",
  "SBI Banking & Financial Services Fund",
  "SBI Banking and PSU Fund",
  "SBI BlueChip Fund",
  "SBI BSE PSU Bank Index Fund",
  "SBI BSE Sensex ETF",
  "SBI BSE Sensex Index Fund",
  "SBI Comma Fund",
  "SBI Conservative Hybrid Fund",
  "SBI Constant Maturity 10 Year Gilt Fund",
  "SBI Consumption Opp Fund",
  "SBI Contra Fund",
  "SBI Corp Bond Fund",
  "SBI CPSE Bond Plus SDL Sep 2026 50:50 Index Fund",
  "SBI CRISIL IBX Gilt Index",
  "SBI CRISIL IBX SDL Index",
  "SBI Dividend Yield Fund",
  "SBI Dynamic Asset Allocation Active FoF",
  "SBI Dynamic Bond Fund",
  "SBI ELSS Tax Saver Fund",
  "SBI Energy Opportunities Fund",
  "SBI Equity Hybrid Fund",
  "SBI Equity Minimum Variance Fund",
  "SBi Equity Savings Fund",
  "SBI Equity Savings Fund",
  "SBI ESG Exclusionary Strategy Fund",
  "SBI Flexicap Fund",
  "SBI Floating Rate Debt Fund",
  "SBI Focused Fund",
  "SBI Gilt Fund",
  "SBI Healthcare Opp Fund",
  "SBI Income Plus Arbitrage Active FOF",
  "SBI Infrastructure Fund",
  "SBI Innovative Opportunities Fund",
  "SBI Large & Midcap Fund",
  "SBI Large Cap Fund",
  "SBI Large Cap Fundd",
  "SBI Liquid Fund",
  "SBI Long Duration Fund",
  "SBI Long Term Equity Fund",
  "SBI Low Duration Fund",
  "SBI Magnum Comma Fund",
  "SBI Magnum Constant Maturity Fund",
  "SBI Magnum Gilt Fund",
  "SBI Magnum Global Fund",
  "SBI Magnum Income Fund",
  "SBI Magnum Low Duration Fund",
  "SBI Magnum Medium Duration Fund",
  "SBI Magnum Midcap Fund",
  "SBI Magnum Ultra Short Duration Fund",
  "SBI Medium Duration Fund",
  "SBI Medium to Long Duration Fund",
  "SBI Midcap Fund",
  "SBI MNC Fund",
  "SBI Multi Asset Allocation Fund",
  "SBI Multicap Fund",
  "SBI Nifty 10 yr Benchmark G",
  "SBI Nifty 200 Quality 30 ETF",
  "SBI Nifty 50 ETF",
  "SBI Nifty 500 Index Fund",
  "SBI Nifty Bank ETF",
  "SBI Nifty Bank Index Fund",
  "SBI Nifty Index Fund",
  "SBI Nifty India Consumption Index Fund",
  "SBI Nifty IT Index Fund",
  "SBI Nifty Midcap 150 Index Fund",
  "SBI Nifty Next 50 Index Fund",
  "SBI Nifty Private Bank ETF",
  "SBI Nifty Smallcap 250 Index Fund",
  "SBI Nifty100 Low Volatility 30 Index Fund",
  "SBI Nifty200 Momentum 30 Index Fund",
  "SBI Nifty200 Quality 30 Index Fund",
  "SBI Nifty50 Equal Weight Index Fund",
  "SBI Overnight Fund",
  "SBI PSU Fund",
  "SBI Quant Fund",
  "SBI Savings Fund",
  "SBI Short Term Debt Fund",
  "SBI Small Cap Fund",
  "SBI Technology Opp Fund",
  "SBI Ultra Short Duration Fund",
  "Shriram Aggressive Hybrid Fund",
  "Shriram Balanced Advantage Fund",
  "Shriram ELSS Tax Saver Fund",
  "Shriram Flexi Cap Fund",
  "Shriram Liquid Fund",
  "Shriram Multi Asset Allocation Fund",
  "Shriram Multi Sector Rotation Fund",
  "Shriram Overnight Fund",
  "Sundaram Aggressive Hybrid Fund",
  "Sundaram Arbitrage Fund",
  "Sundaram Balanced Advantage Fund",
  "Sundaram Banking & PSU Fund",
  "Sundaram Business Cycle Fund",
  "Sundaram Conservative Hybrid Fund",
  "Sundaram Consumption Fund",
  "Sundaram Corp Bond Fund",
  "Sundaram Diversified Equity",
  "Sundaram Dividend Yield Fund",
  "Sundaram ELSS Tax Saver Fund",
  "Sundaram Equity Savings Fund",
  "Sundaram Fin Serv Opp Fund",
  "Sundaram Flexi Cap Fund",
  "Sundaram Focused Fund",
  "Sundaram Infra Advantage Fund",
  "Sundaram Large and Mid Cap Fund",
  "Sundaram Large Cap Fund",
  "Sundaram Liquid Fund",
  "Sundaram Low Duration Fund",
  "Sundaram Medium Duration Fund",
  "Sundaram Mid Cap Fund",
  "Sundaram Money Market Fund",
  "Sundaram Multi",
  "Sundaram Multi Asset Allocation Fund",
  "Sundaram Multi Cap Fund",
  "Sundaram Nifty 100 Equal Weight Fund",
  "Sundaram Overnight Fund",
  "Sundaram Services Fund",
  "Sundaram Short Duration Fund",
  "Sundaram Small Cap Fund",
  "Sundaram Ultra Short Duration Fund",
  "Sundaram Value Fund",
  "Tata Aggressive Hybrid Fund",
  "Tata Arbitrage Fund",
  "Tata Balanced Adv Fund",
  "Tata Banking & Financial Services Fund",
  "Tata BSE Quality Index Fund",
  "Tata BSE Select Business Groups Index Fund",
  "Tata BSE Sensex Index Fund",
  "Tata Business Cycle Fund",
  "Tata Corp Bond Fund",
  "Tata CRISIL IBX Gilt Index",
  "Tata Digital India Fund",
  "Tata Dividend Yield Fund",
  "Tata ELSS Fund",
  "Tata ELSS Tax Saver Fund",
  "Tata Equity P/E Fund",
  "Tata Equity Savings Fund",
  "Tata Ethical Fund",
  "Tata Flexi Cap Fund",
  "Tata Floating Rate Fund",
  "Tata Focused Equity Fund",
  "Tata Focused Fund",
  "Tata Gilt Securities Fund",
  "Tata Housing Opportunities Fund",
  "Tata Hybrid Equity Fund",
  "Tata Income Plus Arbitrage Active FOF",
  "Tata India Consumer Fund",
  "Tata India Innovation Fund",
  "Tata India Pharma & Healthcare Fund",
  "Tata Infrastructure Fund",
  "Tata Large & Mid Cap Fund",
  "Tata Large Cap Fund",
  "Tata Liquid Fund",
  "Tata Mid Cap Fund",
  "Tata Mid Cap Growth Fund",
  "Tata Money Market Fund",
  "Tata Multi Asset Allocation Fund",
  "Tata Multi Asset Opp Fund",
  "Tata Multicap Fund",
  "Tata Nifty 50 ETF",
  "Tata NIFTY 50 Index Fund",
  "Tata Nifty Auto Index Fund",
  "Tata Nifty Capital Markets Index Fund",
  "Tata Nifty Financial Services Index Fund",
  "Tata Nifty India Digital ETF",
  "Tata Nifty India Digital ETF FoF",
  "Tata Nifty India Tourism Index Fund",
  "Tata Nifty Midcap 150 Index Fund",
  "Tata Nifty Midcap 150 Momentum 50 Index Fund",
  "Tata Nifty MidSmall Healthcare Index Fund",
  "Tata Nifty Next 50 Index Fund",
  "Tata Nifty Realty Index Fund",
  "Tata Nifty SDL Plus AAA PSU Bond Dec 2027 60:40 Index Fund",
  "Tata Nifty200 Alpha 30 Index Fund",
  "Tata Nifty500 Multicap India Manufacturing 50:30:20 Index Fund",
  "Tata Nifty500 Multicap Infrastructure 50:30:20 Index Fund",
  "Tata Overnight Fund",
  "Tata Resources & Energy Fund",
  "Tata Small Cap Fund",
  "Tata ST Bond Fund",
  "Tata Treasury Advantage Fund",
  "Tata Ultra Short Term Fund",
  "Tata Value Fund",
  "Taurus ELSS Tax Saver Fund",
  "Taurus Ethical Fund",
  "Taurus Flexi Cap Fund",
  "Taurus Large Cap Fund",
  "Taurus Mid Cap Fund",
  "Templeton India Equity Income Fund",
  "Templeton India Value Fund",
  "TRUSTMF Arbitrage Fund",
  "TRUSTMF Banking & PSU Fund",
  "TRUSTMF Corporate Bond Fund",
  "TRUSTMF Flexi Cap Fund",
  "TRUSTMF Liquid Fund",
  "TRUSTMF Money Market Fund",
  "TRUSTMF Multi Cap Fund",
  "TRUSTMF Overnight Fund",
  "TRUSTMF Short Duration Fund",
  "TRUSTMF Small Cap Fund",
  "Union Active Momentum Fund",
  "Union Aggressive Hybrid Fund",
  "Union Arbitrage Fund",
  "Union Balanced Advantage Fund",
  "Union Business Cycle Fund",
  "Union Corporate Bond Fund",
  "Union Diversified Equity All Cap Active FOF",
  "Union Dynamic Bond Fund",
  "Union ELSS Tax Saver Fund",
  "Union Equity Savings Fund",
  "Union Flexi Cap Fund",
  "Union Focused Fund",
  "Union Gilt Fund",
  "Union Income Plus Arbitrage Active FOF",
  "Union Innovation & Opp Fund",
  "Union Large & Midcap Fund",
  "Union Largecap Fund",
  "Union Liquid Fund",
  "Union Low Duration Fund",
  "Union Midcap Fund",
  "Union Money Market Fund",
  "Union Multi Asset Allocation Fund",
  "Union Multicap Fund",
  "Union Overnight Fund",
  "Union Short Duration Fund",
  "Union Small Cap Fund",
  "Union Value Fund",
  "UTI",
  "UTI Aggressive Hybrid Fund",
  "UTI Arbitrage Fund",
  "UTI Balanced Advantage Fund",
  "UTI Banking & PSU Fund",
  "UTI Banking and Financial Services Fund",
  "UTI BSE Housing Index Fund",
  "UTI BSE Low Volatility Index Fund",
  "UTI BSE Sensex ETF",
  "UTI BSE Sensex Index Fund",
  "UTI Conservative Hybrid Fund",
  "UTI Corporate Bond Fund",
  "UTI Dividend Yield Fund",
  "UTI Dynamic Bond Fund",
  "UTI ELSS Tax Saver Fund",
  "UTI Equity Savings Fund",
  "UTI Flexi Cap Fund",
  "UTI Floater Fund",
  "UTI Focused Fund",
  "UTI Gilt Fund",
  "UTI Gilt Fund with 10 year Constant Duration",
  "UTI Healthcare Fund",
  "UTI Income Plus Arbitrage Active FoF",
  "UTI India Consumer Fund",
  "UTI Infrastructure Fund",
  "UTI Innovation Fund",
  "UTI Large & Mid Cap Fund",
  "UTI Large Cap Fund",
  "UTI Liquid Fund",
  "UTI Long Duration Fund",
  "UTI Low Duration Fund",
  "UTI Medium Duration Fund",
  "UTI Medium to Long Duration Fund",
  "UTI Mid Cap Fund",
  "UTI MNC Fund",
  "UTI Money Market Fund",
  "UTI Multi Asset Allocation Fund",
  "UTI Multi Cap Fund",
  "UTI Nifty 50 ETF",
  "UTI Nifty 50 Index Fund",
  "UTI Nifty 500 Value 50 Index Fund",
  "UTI Nifty Alpha Low",
  "UTI Nifty India Manufacturing Index Fund",
  "UTI Nifty Midcap 150 Index Fund",
  "UTI Nifty Midcap 150 Quality 50 Index Fund",
  "UTI Nifty Midsmallcap 400 Momentum Quality 100 Index Fund",
  "UTI Nifty Next 50 Index Fund",
  "UTI Nifty Private Bank Index Fund",
  "UTI Nifty200 Momentum 30 Index Fund",
  "UTI Nifty200 Quality 30 Index Fund",
  "UTI NIFTY50 Equal Weight Index Fund",
  "UTI Overnight Fund",
  "UTI Quant Fund",
  "UTI Short Duration Fund",
  "UTI Small Cap Fund",
  "UTI Transportation & Logistics Fund",
  "UTI Ultra Short Duration Fund",
  "UTI Value Fund",
  "WOC Arbitrage Fund",
  "WOC Balanced Advantage Fund",
  "WOC Balanced Hybrid Fund",
  "WOC Banking & Financial Services Fund",
  "WOC Digital Bharat Fund",
  "WOC ELSS Tax Saver Fund",
  "WOC Equity Savings Fund",
  "WOC ESG Best",
  "WOC Flexi Cap Fund",
  "WOC Large & Mid Cap Fund",
  "WOC Large Cap Fund",
  "WOC Liquid Fund",
  "WOC Mid Cap Fund",
  "WOC Multi Asset Allocation Fund",
  "WOC Multi Cap Fund",
  "WOC Pharma and Healthcare Fund",
  "WOC Quality Equity Fund",
  "WOC Special Opp Fund",
  "WOC Ultra Short Duration Fund",
];

export default MF_NAMES;
